package customsecurityattributeaudit

import (
	"context"
	"fmt"
	"net/http"

	"github.com/hashicorp/go-azure-sdk/microsoft-graph/common-types/beta"
	"github.com/hashicorp/go-azure-sdk/sdk/client"
	"github.com/hashicorp/go-azure-sdk/sdk/odata"
)

// Copyright (c) HashiCorp Inc. All rights reserved.
// Licensed under the MIT License. See NOTICE.txt in the project root for license information.

type ListCustomSecurityAttributeAuditsOperationResponse struct {
	HttpResponse *http.Response
	OData        *odata.OData
	Model        *[]beta.CustomSecurityAttributeAudit
}

type ListCustomSecurityAttributeAuditsCompleteResult struct {
	LatestHttpResponse *http.Response
	Items              []beta.CustomSecurityAttributeAudit
}

type ListCustomSecurityAttributeAuditsOperationOptions struct {
	Count    *bool
	Expand   *odata.Expand
	Filter   *string
	Metadata *odata.Metadata
	OrderBy  *odata.OrderBy
	Search   *string
	Select   *[]string
	Skip     *int64
	Top      *int64
}

func DefaultListCustomSecurityAttributeAuditsOperationOptions() ListCustomSecurityAttributeAuditsOperationOptions {
	return ListCustomSecurityAttributeAuditsOperationOptions{}
}

func (o ListCustomSecurityAttributeAuditsOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}

	return &out
}

func (o ListCustomSecurityAttributeAuditsOperationOptions) ToOData() *odata.Query {
	out := odata.Query{}
	if o.Count != nil {
		out.Count = *o.Count
	}
	if o.Expand != nil {
		out.Expand = *o.Expand
	}
	if o.Filter != nil {
		out.Filter = *o.Filter
	}
	if o.Metadata != nil {
		out.Metadata = *o.Metadata
	}
	if o.OrderBy != nil {
		out.OrderBy = *o.OrderBy
	}
	if o.Search != nil {
		out.Search = *o.Search
	}
	if o.Select != nil {
		out.Select = *o.Select
	}
	if o.Skip != nil {
		out.Skip = int(*o.Skip)
	}
	if o.Top != nil {
		out.Top = int(*o.Top)
	}
	return &out
}

func (o ListCustomSecurityAttributeAuditsOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}

	return &out
}

type ListCustomSecurityAttributeAuditsCustomPager struct {
	NextLink *odata.Link `json:"@odata.nextLink"`
}

func (p *ListCustomSecurityAttributeAuditsCustomPager) NextPageLink() *odata.Link {
	defer func() {
		p.NextLink = nil
	}()

	return p.NextLink
}

// ListCustomSecurityAttributeAudits - List customSecurityAttributeAudits. Get the list of audit logs generated by
// activities related to custom security attribute management in Microsoft Entra ID.
func (c CustomSecurityAttributeAuditClient) ListCustomSecurityAttributeAudits(ctx context.Context, options ListCustomSecurityAttributeAuditsOperationOptions) (result ListCustomSecurityAttributeAuditsOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json; charset=utf-8",
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Pager:         &ListCustomSecurityAttributeAuditsCustomPager{},
		Path:          "/auditLogs/customSecurityAttributeAudits",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.ExecutePaged(ctx)
	if resp != nil {
		result.OData = resp.OData
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var values struct {
		Values *[]beta.CustomSecurityAttributeAudit `json:"value"`
	}
	if err = resp.Unmarshal(&values); err != nil {
		return
	}

	result.Model = values.Values

	return
}

// ListCustomSecurityAttributeAuditsComplete retrieves all the results into a single object
func (c CustomSecurityAttributeAuditClient) ListCustomSecurityAttributeAuditsComplete(ctx context.Context, options ListCustomSecurityAttributeAuditsOperationOptions) (ListCustomSecurityAttributeAuditsCompleteResult, error) {
	return c.ListCustomSecurityAttributeAuditsCompleteMatchingPredicate(ctx, options, CustomSecurityAttributeAuditOperationPredicate{})
}

// ListCustomSecurityAttributeAuditsCompleteMatchingPredicate retrieves all the results and then applies the predicate
func (c CustomSecurityAttributeAuditClient) ListCustomSecurityAttributeAuditsCompleteMatchingPredicate(ctx context.Context, options ListCustomSecurityAttributeAuditsOperationOptions, predicate CustomSecurityAttributeAuditOperationPredicate) (result ListCustomSecurityAttributeAuditsCompleteResult, err error) {
	items := make([]beta.CustomSecurityAttributeAudit, 0)

	resp, err := c.ListCustomSecurityAttributeAudits(ctx, options)
	if err != nil {
		result.LatestHttpResponse = resp.HttpResponse
		err = fmt.Errorf("loading results: %+v", err)
		return
	}
	if resp.Model != nil {
		for _, v := range *resp.Model {
			if predicate.Matches(v) {
				items = append(items, v)
			}
		}
	}

	result = ListCustomSecurityAttributeAuditsCompleteResult{
		LatestHttpResponse: resp.HttpResponse,
		Items:              items,
	}
	return
}
