package beta

// Copyright (c) HashiCorp Inc. All rights reserved.
// Licensed under the MIT License. See NOTICE.txt in the project root for license information.

type IosManagedAppProtection struct {
	AllowedDataIngestionLocations                  *IosManagedAppProtectionAllowedDataIngestionLocations           `json:"allowedDataIngestionLocations,omitempty"`
	AllowedDataStorageLocations                    *IosManagedAppProtectionAllowedDataStorageLocations             `json:"allowedDataStorageLocations,omitempty"`
	AllowedInboundDataTransferSources              *IosManagedAppProtectionAllowedInboundDataTransferSources       `json:"allowedInboundDataTransferSources,omitempty"`
	AllowedIosDeviceModels                         *string                                                         `json:"allowedIosDeviceModels,omitempty"`
	AllowedOutboundClipboardSharingExceptionLength *int64                                                          `json:"allowedOutboundClipboardSharingExceptionLength,omitempty"`
	AllowedOutboundClipboardSharingLevel           *IosManagedAppProtectionAllowedOutboundClipboardSharingLevel    `json:"allowedOutboundClipboardSharingLevel,omitempty"`
	AllowedOutboundDataTransferDestinations        *IosManagedAppProtectionAllowedOutboundDataTransferDestinations `json:"allowedOutboundDataTransferDestinations,omitempty"`
	AppActionIfDeviceComplianceRequired            *IosManagedAppProtectionAppActionIfDeviceComplianceRequired     `json:"appActionIfDeviceComplianceRequired,omitempty"`
	AppActionIfIosDeviceModelNotAllowed            *IosManagedAppProtectionAppActionIfIosDeviceModelNotAllowed     `json:"appActionIfIosDeviceModelNotAllowed,omitempty"`
	AppActionIfMaximumPinRetriesExceeded           *IosManagedAppProtectionAppActionIfMaximumPinRetriesExceeded    `json:"appActionIfMaximumPinRetriesExceeded,omitempty"`
	AppActionIfUnableToAuthenticateUser            *IosManagedAppProtectionAppActionIfUnableToAuthenticateUser     `json:"appActionIfUnableToAuthenticateUser,omitempty"`
	AppDataEncryptionType                          *IosManagedAppProtectionAppDataEncryptionType                   `json:"appDataEncryptionType,omitempty"`
	AppGroupType                                   *IosManagedAppProtectionAppGroupType                            `json:"appGroupType,omitempty"`
	Apps                                           *[]ManagedMobileApp                                             `json:"apps,omitempty"`
	Assignments                                    *[]TargetedManagedAppPolicyAssignment                           `json:"assignments,omitempty"`
	BlockDataIngestionIntoOrganizationDocuments    *bool                                                           `json:"blockDataIngestionIntoOrganizationDocuments,omitempty"`
	ContactSyncBlocked                             *bool                                                           `json:"contactSyncBlocked,omitempty"`
	CreatedDateTime                                *string                                                         `json:"createdDateTime,omitempty"`
	CustomBrowserProtocol                          *string                                                         `json:"customBrowserProtocol,omitempty"`
	CustomDialerAppProtocol                        *string                                                         `json:"customDialerAppProtocol,omitempty"`
	DataBackupBlocked                              *bool                                                           `json:"dataBackupBlocked,omitempty"`
	DeployedAppCount                               *int64                                                          `json:"deployedAppCount,omitempty"`
	DeploymentSummary                              *ManagedAppPolicyDeploymentSummary                              `json:"deploymentSummary,omitempty"`
	Description                                    *string                                                         `json:"description,omitempty"`
	DeviceComplianceRequired                       *bool                                                           `json:"deviceComplianceRequired,omitempty"`
	DialerRestrictionLevel                         *IosManagedAppProtectionDialerRestrictionLevel                  `json:"dialerRestrictionLevel,omitempty"`
	DisableAppPinIfDevicePinIsSet                  *bool                                                           `json:"disableAppPinIfDevicePinIsSet,omitempty"`
	DisableProtectionOfManagedOutboundOpenInData   *bool                                                           `json:"disableProtectionOfManagedOutboundOpenInData,omitempty"`
	DisplayName                                    *string                                                         `json:"displayName,omitempty"`
	ExemptedAppProtocols                           *[]KeyValuePair                                                 `json:"exemptedAppProtocols,omitempty"`
	ExemptedUniversalLinks                         *[]string                                                       `json:"exemptedUniversalLinks,omitempty"`
	FaceIdBlocked                                  *bool                                                           `json:"faceIdBlocked,omitempty"`
	FilterOpenInToOnlyManagedApps                  *bool                                                           `json:"filterOpenInToOnlyManagedApps,omitempty"`
	FingerprintBlocked                             *bool                                                           `json:"fingerprintBlocked,omitempty"`
	GracePeriodToBlockAppsDuringOffClockHours      *string                                                         `json:"gracePeriodToBlockAppsDuringOffClockHours,omitempty"`
	Id                                             *string                                                         `json:"id,omitempty"`
	IsAssigned                                     *bool                                                           `json:"isAssigned,omitempty"`
	LastModifiedDateTime                           *string                                                         `json:"lastModifiedDateTime,omitempty"`
	ManagedBrowser                                 *IosManagedAppProtectionManagedBrowser                          `json:"managedBrowser,omitempty"`
	ManagedBrowserToOpenLinksRequired              *bool                                                           `json:"managedBrowserToOpenLinksRequired,omitempty"`
	ManagedUniversalLinks                          *[]string                                                       `json:"managedUniversalLinks,omitempty"`
	MaximumAllowedDeviceThreatLevel                *IosManagedAppProtectionMaximumAllowedDeviceThreatLevel         `json:"maximumAllowedDeviceThreatLevel,omitempty"`
	MaximumPinRetries                              *int64                                                          `json:"maximumPinRetries,omitempty"`
	MaximumRequiredOsVersion                       *string                                                         `json:"maximumRequiredOsVersion,omitempty"`
	MaximumWarningOsVersion                        *string                                                         `json:"maximumWarningOsVersion,omitempty"`
	MaximumWipeOsVersion                           *string                                                         `json:"maximumWipeOsVersion,omitempty"`
	MessagingRedirectAppUrlScheme                  *string                                                         `json:"messagingRedirectAppUrlScheme,omitempty"`
	MinimumPinLength                               *int64                                                          `json:"minimumPinLength,omitempty"`
	MinimumRequiredAppVersion                      *string                                                         `json:"minimumRequiredAppVersion,omitempty"`
	MinimumRequiredOsVersion                       *string                                                         `json:"minimumRequiredOsVersion,omitempty"`
	MinimumRequiredSdkVersion                      *string                                                         `json:"minimumRequiredSdkVersion,omitempty"`
	MinimumWarningAppVersion                       *string                                                         `json:"minimumWarningAppVersion,omitempty"`
	MinimumWarningOsVersion                        *string                                                         `json:"minimumWarningOsVersion,omitempty"`
	MinimumWarningSdkVersion                       *string                                                         `json:"minimumWarningSdkVersion,omitempty"`
	MinimumWipeAppVersion                          *string                                                         `json:"minimumWipeAppVersion,omitempty"`
	MinimumWipeOsVersion                           *string                                                         `json:"minimumWipeOsVersion,omitempty"`
	MinimumWipeSdkVersion                          *string                                                         `json:"minimumWipeSdkVersion,omitempty"`
	MobileThreatDefensePartnerPriority             *IosManagedAppProtectionMobileThreatDefensePartnerPriority      `json:"mobileThreatDefensePartnerPriority,omitempty"`
	MobileThreatDefenseRemediationAction           *IosManagedAppProtectionMobileThreatDefenseRemediationAction    `json:"mobileThreatDefenseRemediationAction,omitempty"`
	NotificationRestriction                        *IosManagedAppProtectionNotificationRestriction                 `json:"notificationRestriction,omitempty"`
	ODataType                                      *string                                                         `json:"@odata.type,omitempty"`
	OrganizationalCredentialsRequired              *bool                                                           `json:"organizationalCredentialsRequired,omitempty"`
	PeriodBeforePinReset                           *string                                                         `json:"periodBeforePinReset,omitempty"`
	PeriodOfflineBeforeAccessCheck                 *string                                                         `json:"periodOfflineBeforeAccessCheck,omitempty"`
	PeriodOfflineBeforeWipeIsEnforced              *string                                                         `json:"periodOfflineBeforeWipeIsEnforced,omitempty"`
	PeriodOnlineBeforeAccessCheck                  *string                                                         `json:"periodOnlineBeforeAccessCheck,omitempty"`
	PinCharacterSet                                *IosManagedAppProtectionPinCharacterSet                         `json:"pinCharacterSet,omitempty"`
	PinRequired                                    *bool                                                           `json:"pinRequired,omitempty"`
	PinRequiredInsteadOfBiometricTimeout           *string                                                         `json:"pinRequiredInsteadOfBiometricTimeout,omitempty"`
	PreviousPinBlockCount                          *int64                                                          `json:"previousPinBlockCount,omitempty"`
	PrintBlocked                                   *bool                                                           `json:"printBlocked,omitempty"`
	ProtectInboundDataFromUnknownSources           *bool                                                           `json:"protectInboundDataFromUnknownSources,omitempty"`
	ProtectedMessagingRedirectAppType              *IosManagedAppProtectionProtectedMessagingRedirectAppType       `json:"protectedMessagingRedirectAppType,omitempty"`
	RoleScopeTagIds                                *[]string                                                       `json:"roleScopeTagIds,omitempty"`
	SaveAsBlocked                                  *bool                                                           `json:"saveAsBlocked,omitempty"`
	SimplePinBlocked                               *bool                                                           `json:"simplePinBlocked,omitempty"`
	TargetedAppManagementLevels                    *IosManagedAppProtectionTargetedAppManagementLevels             `json:"targetedAppManagementLevels,omitempty"`
	ThirdPartyKeyboardsBlocked                     *bool                                                           `json:"thirdPartyKeyboardsBlocked,omitempty"`
	Version                                        *string                                                         `json:"version,omitempty"`
}
