package beta

// Copyright (c) HashiCorp Inc. All rights reserved.
// Licensed under the MIT License. See NOTICE.txt in the project root for license information.

type AndroidDeviceOwnerGeneralDeviceConfiguration struct {
	AccountsBlockModification                                *bool                                                                                         `json:"accountsBlockModification,omitempty"`
	AndroidDeviceOwnerDelegatedScopeAppSettings              *[]AndroidDeviceOwnerDelegatedScopeAppSetting                                                 `json:"androidDeviceOwnerDelegatedScopeAppSettings,omitempty"`
	AppsAllowInstallFromUnknownSources                       *bool                                                                                         `json:"appsAllowInstallFromUnknownSources,omitempty"`
	AppsAutoUpdatePolicy                                     *AndroidDeviceOwnerGeneralDeviceConfigurationAppsAutoUpdatePolicy                             `json:"appsAutoUpdatePolicy,omitempty"`
	AppsDefaultPermissionPolicy                              *AndroidDeviceOwnerGeneralDeviceConfigurationAppsDefaultPermissionPolicy                      `json:"appsDefaultPermissionPolicy,omitempty"`
	AppsRecommendSkippingFirstUseHints                       *bool                                                                                         `json:"appsRecommendSkippingFirstUseHints,omitempty"`
	Assignments                                              *[]DeviceConfigurationAssignment                                                              `json:"assignments,omitempty"`
	AzureAdSharedDeviceDataClearApps                         *[]AppListItem                                                                                `json:"azureAdSharedDeviceDataClearApps,omitempty"`
	BluetoothBlockConfiguration                              *bool                                                                                         `json:"bluetoothBlockConfiguration,omitempty"`
	BluetoothBlockContactSharing                             *bool                                                                                         `json:"bluetoothBlockContactSharing,omitempty"`
	CameraBlocked                                            *bool                                                                                         `json:"cameraBlocked,omitempty"`
	CellularBlockWiFiTethering                               *bool                                                                                         `json:"cellularBlockWiFiTethering,omitempty"`
	CertificateCredentialConfigurationDisabled               *bool                                                                                         `json:"certificateCredentialConfigurationDisabled,omitempty"`
	CreatedDateTime                                          *string                                                                                       `json:"createdDateTime,omitempty"`
	CrossProfilePoliciesAllowCopyPaste                       *bool                                                                                         `json:"crossProfilePoliciesAllowCopyPaste,omitempty"`
	CrossProfilePoliciesAllowDataSharing                     *AndroidDeviceOwnerGeneralDeviceConfigurationCrossProfilePoliciesAllowDataSharing             `json:"crossProfilePoliciesAllowDataSharing,omitempty"`
	CrossProfilePoliciesShowWorkContactsInPersonalProfile    *bool                                                                                         `json:"crossProfilePoliciesShowWorkContactsInPersonalProfile,omitempty"`
	DataRoamingBlocked                                       *bool                                                                                         `json:"dataRoamingBlocked,omitempty"`
	DateTimeConfigurationBlocked                             *bool                                                                                         `json:"dateTimeConfigurationBlocked,omitempty"`
	Description                                              *string                                                                                       `json:"description,omitempty"`
	DetailedHelpText                                         *AndroidDeviceOwnerUserFacingMessage                                                          `json:"detailedHelpText,omitempty"`
	DeviceLocationMode                                       *AndroidDeviceOwnerGeneralDeviceConfigurationDeviceLocationMode                               `json:"deviceLocationMode,omitempty"`
	DeviceManagementApplicabilityRuleDeviceMode              *DeviceManagementApplicabilityRuleDeviceMode                                                  `json:"deviceManagementApplicabilityRuleDeviceMode,omitempty"`
	DeviceManagementApplicabilityRuleOsEdition               *DeviceManagementApplicabilityRuleOsEdition                                                   `json:"deviceManagementApplicabilityRuleOsEdition,omitempty"`
	DeviceManagementApplicabilityRuleOsVersion               *DeviceManagementApplicabilityRuleOsVersion                                                   `json:"deviceManagementApplicabilityRuleOsVersion,omitempty"`
	DeviceOwnerLockScreenMessage                             *AndroidDeviceOwnerUserFacingMessage                                                          `json:"deviceOwnerLockScreenMessage,omitempty"`
	DeviceSettingStateSummaries                              *[]SettingStateDeviceSummary                                                                  `json:"deviceSettingStateSummaries,omitempty"`
	DeviceStatusOverview                                     *DeviceConfigurationDeviceOverview                                                            `json:"deviceStatusOverview,omitempty"`
	DeviceStatuses                                           *[]DeviceConfigurationDeviceStatus                                                            `json:"deviceStatuses,omitempty"`
	DisplayName                                              *string                                                                                       `json:"displayName,omitempty"`
	EnrollmentProfile                                        *AndroidDeviceOwnerGeneralDeviceConfigurationEnrollmentProfile                                `json:"enrollmentProfile,omitempty"`
	FactoryResetBlocked                                      *bool                                                                                         `json:"factoryResetBlocked,omitempty"`
	FactoryResetDeviceAdministratorEmails                    *[]string                                                                                     `json:"factoryResetDeviceAdministratorEmails,omitempty"`
	GlobalProxy                                              *AndroidDeviceOwnerGlobalProxy                                                                `json:"globalProxy,omitempty"`
	GoogleAccountsBlocked                                    *bool                                                                                         `json:"googleAccountsBlocked,omitempty"`
	GroupAssignments                                         *[]DeviceConfigurationGroupAssignment                                                         `json:"groupAssignments,omitempty"`
	Id                                                       *string                                                                                       `json:"id,omitempty"`
	KioskCustomizationDeviceSettingsBlocked                  *bool                                                                                         `json:"kioskCustomizationDeviceSettingsBlocked,omitempty"`
	KioskCustomizationPowerButtonActionsBlocked              *bool                                                                                         `json:"kioskCustomizationPowerButtonActionsBlocked,omitempty"`
	KioskCustomizationStatusBar                              *AndroidDeviceOwnerGeneralDeviceConfigurationKioskCustomizationStatusBar                      `json:"kioskCustomizationStatusBar,omitempty"`
	KioskCustomizationSystemErrorWarnings                    *bool                                                                                         `json:"kioskCustomizationSystemErrorWarnings,omitempty"`
	KioskCustomizationSystemNavigation                       *AndroidDeviceOwnerGeneralDeviceConfigurationKioskCustomizationSystemNavigation               `json:"kioskCustomizationSystemNavigation,omitempty"`
	KioskModeAppOrderEnabled                                 *bool                                                                                         `json:"kioskModeAppOrderEnabled,omitempty"`
	KioskModeAppPositions                                    *[]AndroidDeviceOwnerKioskModeAppPositionItem                                                 `json:"kioskModeAppPositions,omitempty"`
	KioskModeApps                                            *[]AppListItem                                                                                `json:"kioskModeApps,omitempty"`
	KioskModeAppsInFolderOrderedByName                       *bool                                                                                         `json:"kioskModeAppsInFolderOrderedByName,omitempty"`
	KioskModeBluetoothConfigurationEnabled                   *bool                                                                                         `json:"kioskModeBluetoothConfigurationEnabled,omitempty"`
	KioskModeDebugMenuEasyAccessEnabled                      *bool                                                                                         `json:"kioskModeDebugMenuEasyAccessEnabled,omitempty"`
	KioskModeExitCode                                        *string                                                                                       `json:"kioskModeExitCode,omitempty"`
	KioskModeFlashlightConfigurationEnabled                  *bool                                                                                         `json:"kioskModeFlashlightConfigurationEnabled,omitempty"`
	KioskModeFolderIcon                                      *AndroidDeviceOwnerGeneralDeviceConfigurationKioskModeFolderIcon                              `json:"kioskModeFolderIcon,omitempty"`
	KioskModeGridHeight                                      *int64                                                                                        `json:"kioskModeGridHeight,omitempty"`
	KioskModeGridWidth                                       *int64                                                                                        `json:"kioskModeGridWidth,omitempty"`
	KioskModeIconSize                                        *AndroidDeviceOwnerGeneralDeviceConfigurationKioskModeIconSize                                `json:"kioskModeIconSize,omitempty"`
	KioskModeLockHomeScreen                                  *bool                                                                                         `json:"kioskModeLockHomeScreen,omitempty"`
	KioskModeManagedFolders                                  *[]AndroidDeviceOwnerKioskModeManagedFolder                                                   `json:"kioskModeManagedFolders,omitempty"`
	KioskModeManagedHomeScreenAutoSignout                    *bool                                                                                         `json:"kioskModeManagedHomeScreenAutoSignout,omitempty"`
	KioskModeManagedHomeScreenInactiveSignOutDelayInSeconds  *int64                                                                                        `json:"kioskModeManagedHomeScreenInactiveSignOutDelayInSeconds,omitempty"`
	KioskModeManagedHomeScreenInactiveSignOutNoticeInSeconds *int64                                                                                        `json:"kioskModeManagedHomeScreenInactiveSignOutNoticeInSeconds,omitempty"`
	KioskModeManagedHomeScreenPinComplexity                  *AndroidDeviceOwnerGeneralDeviceConfigurationKioskModeManagedHomeScreenPinComplexity          `json:"kioskModeManagedHomeScreenPinComplexity,omitempty"`
	KioskModeManagedHomeScreenPinRequired                    *bool                                                                                         `json:"kioskModeManagedHomeScreenPinRequired,omitempty"`
	KioskModeManagedHomeScreenPinRequiredToResume            *bool                                                                                         `json:"kioskModeManagedHomeScreenPinRequiredToResume,omitempty"`
	KioskModeManagedHomeScreenSignInBackground               *string                                                                                       `json:"kioskModeManagedHomeScreenSignInBackground,omitempty"`
	KioskModeManagedHomeScreenSignInBrandingLogo             *string                                                                                       `json:"kioskModeManagedHomeScreenSignInBrandingLogo,omitempty"`
	KioskModeManagedHomeScreenSignInEnabled                  *bool                                                                                         `json:"kioskModeManagedHomeScreenSignInEnabled,omitempty"`
	KioskModeManagedSettingsEntryDisabled                    *bool                                                                                         `json:"kioskModeManagedSettingsEntryDisabled,omitempty"`
	KioskModeMediaVolumeConfigurationEnabled                 *bool                                                                                         `json:"kioskModeMediaVolumeConfigurationEnabled,omitempty"`
	KioskModeScreenOrientation                               *AndroidDeviceOwnerGeneralDeviceConfigurationKioskModeScreenOrientation                       `json:"kioskModeScreenOrientation,omitempty"`
	KioskModeScreenSaverConfigurationEnabled                 *bool                                                                                         `json:"kioskModeScreenSaverConfigurationEnabled,omitempty"`
	KioskModeScreenSaverDetectMediaDisabled                  *bool                                                                                         `json:"kioskModeScreenSaverDetectMediaDisabled,omitempty"`
	KioskModeScreenSaverDisplayTimeInSeconds                 *int64                                                                                        `json:"kioskModeScreenSaverDisplayTimeInSeconds,omitempty"`
	KioskModeScreenSaverImageUrl                             *string                                                                                       `json:"kioskModeScreenSaverImageUrl,omitempty"`
	KioskModeScreenSaverStartDelayInSeconds                  *int64                                                                                        `json:"kioskModeScreenSaverStartDelayInSeconds,omitempty"`
	KioskModeShowAppNotificationBadge                        *bool                                                                                         `json:"kioskModeShowAppNotificationBadge,omitempty"`
	KioskModeShowDeviceInfo                                  *bool                                                                                         `json:"kioskModeShowDeviceInfo,omitempty"`
	KioskModeUseManagedHomeScreenApp                         *AndroidDeviceOwnerGeneralDeviceConfigurationKioskModeUseManagedHomeScreenApp                 `json:"kioskModeUseManagedHomeScreenApp,omitempty"`
	KioskModeVirtualHomeButtonEnabled                        *bool                                                                                         `json:"kioskModeVirtualHomeButtonEnabled,omitempty"`
	KioskModeVirtualHomeButtonType                           *AndroidDeviceOwnerGeneralDeviceConfigurationKioskModeVirtualHomeButtonType                   `json:"kioskModeVirtualHomeButtonType,omitempty"`
	KioskModeWallpaperUrl                                    *string                                                                                       `json:"kioskModeWallpaperUrl,omitempty"`
	KioskModeWiFiConfigurationEnabled                        *bool                                                                                         `json:"kioskModeWiFiConfigurationEnabled,omitempty"`
	KioskModeWifiAllowedSsids                                *[]string                                                                                     `json:"kioskModeWifiAllowedSsids,omitempty"`
	LastModifiedDateTime                                     *string                                                                                       `json:"lastModifiedDateTime,omitempty"`
	LocateDeviceLostModeEnabled                              *bool                                                                                         `json:"locateDeviceLostModeEnabled,omitempty"`
	LocateDeviceUserlessDisabled                             *bool                                                                                         `json:"locateDeviceUserlessDisabled,omitempty"`
	MicrophoneForceMute                                      *bool                                                                                         `json:"microphoneForceMute,omitempty"`
	MicrosoftLauncherConfigurationEnabled                    *bool                                                                                         `json:"microsoftLauncherConfigurationEnabled,omitempty"`
	MicrosoftLauncherCustomWallpaperAllowUserModification    *bool                                                                                         `json:"microsoftLauncherCustomWallpaperAllowUserModification,omitempty"`
	MicrosoftLauncherCustomWallpaperEnabled                  *bool                                                                                         `json:"microsoftLauncherCustomWallpaperEnabled,omitempty"`
	MicrosoftLauncherCustomWallpaperImageUrl                 *string                                                                                       `json:"microsoftLauncherCustomWallpaperImageUrl,omitempty"`
	MicrosoftLauncherDockPresenceAllowUserModification       *bool                                                                                         `json:"microsoftLauncherDockPresenceAllowUserModification,omitempty"`
	MicrosoftLauncherDockPresenceConfiguration               *AndroidDeviceOwnerGeneralDeviceConfigurationMicrosoftLauncherDockPresenceConfiguration       `json:"microsoftLauncherDockPresenceConfiguration,omitempty"`
	MicrosoftLauncherFeedAllowUserModification               *bool                                                                                         `json:"microsoftLauncherFeedAllowUserModification,omitempty"`
	MicrosoftLauncherFeedEnabled                             *bool                                                                                         `json:"microsoftLauncherFeedEnabled,omitempty"`
	MicrosoftLauncherSearchBarPlacementConfiguration         *AndroidDeviceOwnerGeneralDeviceConfigurationMicrosoftLauncherSearchBarPlacementConfiguration `json:"microsoftLauncherSearchBarPlacementConfiguration,omitempty"`
	NetworkEscapeHatchAllowed                                *bool                                                                                         `json:"networkEscapeHatchAllowed,omitempty"`
	NfcBlockOutgoingBeam                                     *bool                                                                                         `json:"nfcBlockOutgoingBeam,omitempty"`
	ODataType                                                *string                                                                                       `json:"@odata.type,omitempty"`
	PasswordBlockKeyguard                                    *bool                                                                                         `json:"passwordBlockKeyguard,omitempty"`
	PasswordBlockKeyguardFeatures                            *AndroidDeviceOwnerGeneralDeviceConfigurationPasswordBlockKeyguardFeatures                    `json:"passwordBlockKeyguardFeatures,omitempty"`
	PasswordExpirationDays                                   *int64                                                                                        `json:"passwordExpirationDays,omitempty"`
	PasswordMinimumLength                                    *int64                                                                                        `json:"passwordMinimumLength,omitempty"`
	PasswordMinimumLetterCharacters                          *int64                                                                                        `json:"passwordMinimumLetterCharacters,omitempty"`
	PasswordMinimumLowerCaseCharacters                       *int64                                                                                        `json:"passwordMinimumLowerCaseCharacters,omitempty"`
	PasswordMinimumNonLetterCharacters                       *int64                                                                                        `json:"passwordMinimumNonLetterCharacters,omitempty"`
	PasswordMinimumNumericCharacters                         *int64                                                                                        `json:"passwordMinimumNumericCharacters,omitempty"`
	PasswordMinimumSymbolCharacters                          *int64                                                                                        `json:"passwordMinimumSymbolCharacters,omitempty"`
	PasswordMinimumUpperCaseCharacters                       *int64                                                                                        `json:"passwordMinimumUpperCaseCharacters,omitempty"`
	PasswordMinutesOfInactivityBeforeScreenTimeout           *int64                                                                                        `json:"passwordMinutesOfInactivityBeforeScreenTimeout,omitempty"`
	PasswordPreviousPasswordCountToBlock                     *int64                                                                                        `json:"passwordPreviousPasswordCountToBlock,omitempty"`
	PasswordRequireUnlock                                    *AndroidDeviceOwnerGeneralDeviceConfigurationPasswordRequireUnlock                            `json:"passwordRequireUnlock,omitempty"`
	PasswordRequiredType                                     *AndroidDeviceOwnerGeneralDeviceConfigurationPasswordRequiredType                             `json:"passwordRequiredType,omitempty"`
	PasswordSignInFailureCountBeforeFactoryReset             *int64                                                                                        `json:"passwordSignInFailureCountBeforeFactoryReset,omitempty"`
	PersonalProfileAppsAllowInstallFromUnknownSources        *bool                                                                                         `json:"personalProfileAppsAllowInstallFromUnknownSources,omitempty"`
	PersonalProfileCameraBlocked                             *bool                                                                                         `json:"personalProfileCameraBlocked,omitempty"`
	PersonalProfilePersonalApplications                      *[]AppListItem                                                                                `json:"personalProfilePersonalApplications,omitempty"`
	PersonalProfilePlayStoreMode                             *AndroidDeviceOwnerGeneralDeviceConfigurationPersonalProfilePlayStoreMode                     `json:"personalProfilePlayStoreMode,omitempty"`
	PersonalProfileScreenCaptureBlocked                      *bool                                                                                         `json:"personalProfileScreenCaptureBlocked,omitempty"`
	PlayStoreMode                                            *AndroidDeviceOwnerGeneralDeviceConfigurationPlayStoreMode                                    `json:"playStoreMode,omitempty"`
	RoleScopeTagIds                                          *[]string                                                                                     `json:"roleScopeTagIds,omitempty"`
	ScreenCaptureBlocked                                     *bool                                                                                         `json:"screenCaptureBlocked,omitempty"`
	SecurityCommonCriteriaModeEnabled                        *bool                                                                                         `json:"securityCommonCriteriaModeEnabled,omitempty"`
	SecurityDeveloperSettingsEnabled                         *bool                                                                                         `json:"securityDeveloperSettingsEnabled,omitempty"`
	SecurityRequireVerifyApps                                *bool                                                                                         `json:"securityRequireVerifyApps,omitempty"`
	ShareDeviceLocationDisabled                              *bool                                                                                         `json:"shareDeviceLocationDisabled,omitempty"`
	ShortHelpText                                            *AndroidDeviceOwnerUserFacingMessage                                                          `json:"shortHelpText,omitempty"`
	StatusBarBlocked                                         *bool                                                                                         `json:"statusBarBlocked,omitempty"`
	StayOnModes                                              *AndroidDeviceOwnerGeneralDeviceConfigurationStayOnModes                                      `json:"stayOnModes,omitempty"`
	StorageAllowUsb                                          *bool                                                                                         `json:"storageAllowUsb,omitempty"`
	StorageBlockExternalMedia                                *bool                                                                                         `json:"storageBlockExternalMedia,omitempty"`
	StorageBlockUsbFileTransfer                              *bool                                                                                         `json:"storageBlockUsbFileTransfer,omitempty"`
	SupportsScopeTags                                        *bool                                                                                         `json:"supportsScopeTags,omitempty"`
	SystemUpdateFreezePeriods                                *[]AndroidDeviceOwnerSystemUpdateFreezePeriod                                                 `json:"systemUpdateFreezePeriods,omitempty"`
	SystemUpdateInstallType                                  *AndroidDeviceOwnerGeneralDeviceConfigurationSystemUpdateInstallType                          `json:"systemUpdateInstallType,omitempty"`
	SystemUpdateWindowEndMinutesAfterMidnight                *int64                                                                                        `json:"systemUpdateWindowEndMinutesAfterMidnight,omitempty"`
	SystemUpdateWindowStartMinutesAfterMidnight              *int64                                                                                        `json:"systemUpdateWindowStartMinutesAfterMidnight,omitempty"`
	SystemWindowsBlocked                                     *bool                                                                                         `json:"systemWindowsBlocked,omitempty"`
	UserStatusOverview                                       *DeviceConfigurationUserOverview                                                              `json:"userStatusOverview,omitempty"`
	UserStatuses                                             *[]DeviceConfigurationUserStatus                                                              `json:"userStatuses,omitempty"`
	UsersBlockAdd                                            *bool                                                                                         `json:"usersBlockAdd,omitempty"`
	UsersBlockRemove                                         *bool                                                                                         `json:"usersBlockRemove,omitempty"`
	Version                                                  *int64                                                                                        `json:"version,omitempty"`
	VolumeBlockAdjustment                                    *bool                                                                                         `json:"volumeBlockAdjustment,omitempty"`
	VpnAlwaysOnLockdownMode                                  *bool                                                                                         `json:"vpnAlwaysOnLockdownMode,omitempty"`
	VpnAlwaysOnPackageIdentifier                             *string                                                                                       `json:"vpnAlwaysOnPackageIdentifier,omitempty"`
	WifiBlockEditConfigurations                              *bool                                                                                         `json:"wifiBlockEditConfigurations,omitempty"`
	WifiBlockEditPolicyDefinedConfigurations                 *bool                                                                                         `json:"wifiBlockEditPolicyDefinedConfigurations,omitempty"`
	WorkProfilePasswordExpirationDays                        *int64                                                                                        `json:"workProfilePasswordExpirationDays,omitempty"`
	WorkProfilePasswordMinimumLength                         *int64                                                                                        `json:"workProfilePasswordMinimumLength,omitempty"`
	WorkProfilePasswordMinimumLetterCharacters               *int64                                                                                        `json:"workProfilePasswordMinimumLetterCharacters,omitempty"`
	WorkProfilePasswordMinimumLowerCaseCharacters            *int64                                                                                        `json:"workProfilePasswordMinimumLowerCaseCharacters,omitempty"`
	WorkProfilePasswordMinimumNonLetterCharacters            *int64                                                                                        `json:"workProfilePasswordMinimumNonLetterCharacters,omitempty"`
	WorkProfilePasswordMinimumNumericCharacters              *int64                                                                                        `json:"workProfilePasswordMinimumNumericCharacters,omitempty"`
	WorkProfilePasswordMinimumSymbolCharacters               *int64                                                                                        `json:"workProfilePasswordMinimumSymbolCharacters,omitempty"`
	WorkProfilePasswordMinimumUpperCaseCharacters            *int64                                                                                        `json:"workProfilePasswordMinimumUpperCaseCharacters,omitempty"`
	WorkProfilePasswordPreviousPasswordCountToBlock          *int64                                                                                        `json:"workProfilePasswordPreviousPasswordCountToBlock,omitempty"`
	WorkProfilePasswordRequireUnlock                         *AndroidDeviceOwnerGeneralDeviceConfigurationWorkProfilePasswordRequireUnlock                 `json:"workProfilePasswordRequireUnlock,omitempty"`
	WorkProfilePasswordRequiredType                          *AndroidDeviceOwnerGeneralDeviceConfigurationWorkProfilePasswordRequiredType                  `json:"workProfilePasswordRequiredType,omitempty"`
	WorkProfilePasswordSignInFailureCountBeforeFactoryReset  *int64                                                                                        `json:"workProfilePasswordSignInFailureCountBeforeFactoryReset,omitempty"`
}
