package beta

// Copyright (c) HashiCorp Inc. All rights reserved.
// Licensed under the MIT License. See NOTICE.txt in the project root for license information.

type Windows10GeneralConfiguration struct {
	AccountsBlockAddingNonMicrosoftAccountEmail           *bool                                                                         `json:"accountsBlockAddingNonMicrosoftAccountEmail,omitempty"`
	ActivateAppsWithVoice                                 *Windows10GeneralConfigurationActivateAppsWithVoice                           `json:"activateAppsWithVoice,omitempty"`
	AntiTheftModeBlocked                                  *bool                                                                         `json:"antiTheftModeBlocked,omitempty"`
	AppManagementMSIAllowUserControlOverInstall           *bool                                                                         `json:"appManagementMSIAllowUserControlOverInstall,omitempty"`
	AppManagementMSIAlwaysInstallWithElevatedPrivileges   *bool                                                                         `json:"appManagementMSIAlwaysInstallWithElevatedPrivileges,omitempty"`
	AppManagementPackageFamilyNamesToLaunchAfterLogOn     *[]string                                                                     `json:"appManagementPackageFamilyNamesToLaunchAfterLogOn,omitempty"`
	AppsAllowTrustedAppsSideloading                       *Windows10GeneralConfigurationAppsAllowTrustedAppsSideloading                 `json:"appsAllowTrustedAppsSideloading,omitempty"`
	AppsBlockWindowsStoreOriginatedApps                   *bool                                                                         `json:"appsBlockWindowsStoreOriginatedApps,omitempty"`
	Assignments                                           *[]DeviceConfigurationAssignment                                              `json:"assignments,omitempty"`
	AuthenticationAllowSecondaryDevice                    *bool                                                                         `json:"authenticationAllowSecondaryDevice,omitempty"`
	AuthenticationPreferredAzureADTenantDomainName        *string                                                                       `json:"authenticationPreferredAzureADTenantDomainName,omitempty"`
	AuthenticationWebSignIn                               *Windows10GeneralConfigurationAuthenticationWebSignIn                         `json:"authenticationWebSignIn,omitempty"`
	BluetoothAllowedServices                              *[]string                                                                     `json:"bluetoothAllowedServices,omitempty"`
	BluetoothBlockAdvertising                             *bool                                                                         `json:"bluetoothBlockAdvertising,omitempty"`
	BluetoothBlockDiscoverableMode                        *bool                                                                         `json:"bluetoothBlockDiscoverableMode,omitempty"`
	BluetoothBlockPrePairing                              *bool                                                                         `json:"bluetoothBlockPrePairing,omitempty"`
	BluetoothBlockPromptedProximalConnections             *bool                                                                         `json:"bluetoothBlockPromptedProximalConnections,omitempty"`
	BluetoothBlocked                                      *bool                                                                         `json:"bluetoothBlocked,omitempty"`
	CameraBlocked                                         *bool                                                                         `json:"cameraBlocked,omitempty"`
	CellularBlockDataWhenRoaming                          *bool                                                                         `json:"cellularBlockDataWhenRoaming,omitempty"`
	CellularBlockVpn                                      *bool                                                                         `json:"cellularBlockVpn,omitempty"`
	CellularBlockVpnWhenRoaming                           *bool                                                                         `json:"cellularBlockVpnWhenRoaming,omitempty"`
	CellularData                                          *Windows10GeneralConfigurationCellularData                                    `json:"cellularData,omitempty"`
	CertificatesBlockManualRootCertificateInstallation    *bool                                                                         `json:"certificatesBlockManualRootCertificateInstallation,omitempty"`
	ConfigureTimeZone                                     *string                                                                       `json:"configureTimeZone,omitempty"`
	ConnectedDevicesServiceBlocked                        *bool                                                                         `json:"connectedDevicesServiceBlocked,omitempty"`
	CopyPasteBlocked                                      *bool                                                                         `json:"copyPasteBlocked,omitempty"`
	CortanaBlocked                                        *bool                                                                         `json:"cortanaBlocked,omitempty"`
	CreatedDateTime                                       *string                                                                       `json:"createdDateTime,omitempty"`
	CryptographyAllowFipsAlgorithmPolicy                  *bool                                                                         `json:"cryptographyAllowFipsAlgorithmPolicy,omitempty"`
	DataProtectionBlockDirectMemoryAccess                 *bool                                                                         `json:"dataProtectionBlockDirectMemoryAccess,omitempty"`
	DefenderBlockEndUserAccess                            *bool                                                                         `json:"defenderBlockEndUserAccess,omitempty"`
	DefenderBlockOnAccessProtection                       *bool                                                                         `json:"defenderBlockOnAccessProtection,omitempty"`
	DefenderCloudBlockLevel                               *Windows10GeneralConfigurationDefenderCloudBlockLevel                         `json:"defenderCloudBlockLevel,omitempty"`
	DefenderCloudExtendedTimeout                          *int64                                                                        `json:"defenderCloudExtendedTimeout,omitempty"`
	DefenderCloudExtendedTimeoutInSeconds                 *int64                                                                        `json:"defenderCloudExtendedTimeoutInSeconds,omitempty"`
	DefenderDaysBeforeDeletingQuarantinedMalware          *int64                                                                        `json:"defenderDaysBeforeDeletingQuarantinedMalware,omitempty"`
	DefenderDetectedMalwareActions                        *DefenderDetectedMalwareActions                                               `json:"defenderDetectedMalwareActions,omitempty"`
	DefenderDisableCatchupFullScan                        *bool                                                                         `json:"defenderDisableCatchupFullScan,omitempty"`
	DefenderDisableCatchupQuickScan                       *bool                                                                         `json:"defenderDisableCatchupQuickScan,omitempty"`
	DefenderFileExtensionsToExclude                       *[]string                                                                     `json:"defenderFileExtensionsToExclude,omitempty"`
	DefenderFilesAndFoldersToExclude                      *[]string                                                                     `json:"defenderFilesAndFoldersToExclude,omitempty"`
	DefenderMonitorFileActivity                           *Windows10GeneralConfigurationDefenderMonitorFileActivity                     `json:"defenderMonitorFileActivity,omitempty"`
	DefenderPotentiallyUnwantedAppAction                  *Windows10GeneralConfigurationDefenderPotentiallyUnwantedAppAction            `json:"defenderPotentiallyUnwantedAppAction,omitempty"`
	DefenderPotentiallyUnwantedAppActionSetting           *Windows10GeneralConfigurationDefenderPotentiallyUnwantedAppActionSetting     `json:"defenderPotentiallyUnwantedAppActionSetting,omitempty"`
	DefenderProcessesToExclude                            *[]string                                                                     `json:"defenderProcessesToExclude,omitempty"`
	DefenderPromptForSampleSubmission                     *Windows10GeneralConfigurationDefenderPromptForSampleSubmission               `json:"defenderPromptForSampleSubmission,omitempty"`
	DefenderRequireBehaviorMonitoring                     *bool                                                                         `json:"defenderRequireBehaviorMonitoring,omitempty"`
	DefenderRequireCloudProtection                        *bool                                                                         `json:"defenderRequireCloudProtection,omitempty"`
	DefenderRequireNetworkInspectionSystem                *bool                                                                         `json:"defenderRequireNetworkInspectionSystem,omitempty"`
	DefenderRequireRealTimeMonitoring                     *bool                                                                         `json:"defenderRequireRealTimeMonitoring,omitempty"`
	DefenderScanArchiveFiles                              *bool                                                                         `json:"defenderScanArchiveFiles,omitempty"`
	DefenderScanDownloads                                 *bool                                                                         `json:"defenderScanDownloads,omitempty"`
	DefenderScanIncomingMail                              *bool                                                                         `json:"defenderScanIncomingMail,omitempty"`
	DefenderScanMappedNetworkDrivesDuringFullScan         *bool                                                                         `json:"defenderScanMappedNetworkDrivesDuringFullScan,omitempty"`
	DefenderScanMaxCpu                                    *int64                                                                        `json:"defenderScanMaxCpu,omitempty"`
	DefenderScanNetworkFiles                              *bool                                                                         `json:"defenderScanNetworkFiles,omitempty"`
	DefenderScanRemovableDrivesDuringFullScan             *bool                                                                         `json:"defenderScanRemovableDrivesDuringFullScan,omitempty"`
	DefenderScanScriptsLoadedInInternetExplorer           *bool                                                                         `json:"defenderScanScriptsLoadedInInternetExplorer,omitempty"`
	DefenderScanType                                      *Windows10GeneralConfigurationDefenderScanType                                `json:"defenderScanType,omitempty"`
	DefenderScheduleScanEnableLowCpuPriority              *bool                                                                         `json:"defenderScheduleScanEnableLowCpuPriority,omitempty"`
	DefenderScheduledQuickScanTime                        *string                                                                       `json:"defenderScheduledQuickScanTime,omitempty"`
	DefenderScheduledScanTime                             *string                                                                       `json:"defenderScheduledScanTime,omitempty"`
	DefenderSignatureUpdateIntervalInHours                *int64                                                                        `json:"defenderSignatureUpdateIntervalInHours,omitempty"`
	DefenderSubmitSamplesConsentType                      *Windows10GeneralConfigurationDefenderSubmitSamplesConsentType                `json:"defenderSubmitSamplesConsentType,omitempty"`
	DefenderSystemScanSchedule                            *Windows10GeneralConfigurationDefenderSystemScanSchedule                      `json:"defenderSystemScanSchedule,omitempty"`
	Description                                           *string                                                                       `json:"description,omitempty"`
	DeveloperUnlockSetting                                *Windows10GeneralConfigurationDeveloperUnlockSetting                          `json:"developerUnlockSetting,omitempty"`
	DeviceManagementApplicabilityRuleDeviceMode           *DeviceManagementApplicabilityRuleDeviceMode                                  `json:"deviceManagementApplicabilityRuleDeviceMode,omitempty"`
	DeviceManagementApplicabilityRuleOsEdition            *DeviceManagementApplicabilityRuleOsEdition                                   `json:"deviceManagementApplicabilityRuleOsEdition,omitempty"`
	DeviceManagementApplicabilityRuleOsVersion            *DeviceManagementApplicabilityRuleOsVersion                                   `json:"deviceManagementApplicabilityRuleOsVersion,omitempty"`
	DeviceManagementBlockFactoryResetOnMobile             *bool                                                                         `json:"deviceManagementBlockFactoryResetOnMobile,omitempty"`
	DeviceManagementBlockManualUnenroll                   *bool                                                                         `json:"deviceManagementBlockManualUnenroll,omitempty"`
	DeviceSettingStateSummaries                           *[]SettingStateDeviceSummary                                                  `json:"deviceSettingStateSummaries,omitempty"`
	DeviceStatusOverview                                  *DeviceConfigurationDeviceOverview                                            `json:"deviceStatusOverview,omitempty"`
	DeviceStatuses                                        *[]DeviceConfigurationDeviceStatus                                            `json:"deviceStatuses,omitempty"`
	DiagnosticsDataSubmissionMode                         *Windows10GeneralConfigurationDiagnosticsDataSubmissionMode                   `json:"diagnosticsDataSubmissionMode,omitempty"`
	DisplayAppListWithGdiDPIScalingTurnedOff              *[]string                                                                     `json:"displayAppListWithGdiDPIScalingTurnedOff,omitempty"`
	DisplayAppListWithGdiDPIScalingTurnedOn               *[]string                                                                     `json:"displayAppListWithGdiDPIScalingTurnedOn,omitempty"`
	DisplayName                                           *string                                                                       `json:"displayName,omitempty"`
	EdgeAllowStartPagesModification                       *bool                                                                         `json:"edgeAllowStartPagesModification,omitempty"`
	EdgeBlockAccessToAboutFlags                           *bool                                                                         `json:"edgeBlockAccessToAboutFlags,omitempty"`
	EdgeBlockAddressBarDropdown                           *bool                                                                         `json:"edgeBlockAddressBarDropdown,omitempty"`
	EdgeBlockAutofill                                     *bool                                                                         `json:"edgeBlockAutofill,omitempty"`
	EdgeBlockCompatibilityList                            *bool                                                                         `json:"edgeBlockCompatibilityList,omitempty"`
	EdgeBlockDeveloperTools                               *bool                                                                         `json:"edgeBlockDeveloperTools,omitempty"`
	EdgeBlockEditFavorites                                *bool                                                                         `json:"edgeBlockEditFavorites,omitempty"`
	EdgeBlockExtensions                                   *bool                                                                         `json:"edgeBlockExtensions,omitempty"`
	EdgeBlockFullScreenMode                               *bool                                                                         `json:"edgeBlockFullScreenMode,omitempty"`
	EdgeBlockInPrivateBrowsing                            *bool                                                                         `json:"edgeBlockInPrivateBrowsing,omitempty"`
	EdgeBlockJavaScript                                   *bool                                                                         `json:"edgeBlockJavaScript,omitempty"`
	EdgeBlockLiveTileDataCollection                       *bool                                                                         `json:"edgeBlockLiveTileDataCollection,omitempty"`
	EdgeBlockPasswordManager                              *bool                                                                         `json:"edgeBlockPasswordManager,omitempty"`
	EdgeBlockPopups                                       *bool                                                                         `json:"edgeBlockPopups,omitempty"`
	EdgeBlockPrelaunch                                    *bool                                                                         `json:"edgeBlockPrelaunch,omitempty"`
	EdgeBlockPrinting                                     *bool                                                                         `json:"edgeBlockPrinting,omitempty"`
	EdgeBlockSavingHistory                                *bool                                                                         `json:"edgeBlockSavingHistory,omitempty"`
	EdgeBlockSearchEngineCustomization                    *bool                                                                         `json:"edgeBlockSearchEngineCustomization,omitempty"`
	EdgeBlockSearchSuggestions                            *bool                                                                         `json:"edgeBlockSearchSuggestions,omitempty"`
	EdgeBlockSendingDoNotTrackHeader                      *bool                                                                         `json:"edgeBlockSendingDoNotTrackHeader,omitempty"`
	EdgeBlockSendingIntranetTrafficToInternetExplorer     *bool                                                                         `json:"edgeBlockSendingIntranetTrafficToInternetExplorer,omitempty"`
	EdgeBlockSideloadingExtensions                        *bool                                                                         `json:"edgeBlockSideloadingExtensions,omitempty"`
	EdgeBlockTabPreloading                                *bool                                                                         `json:"edgeBlockTabPreloading,omitempty"`
	EdgeBlockWebContentOnNewTabPage                       *bool                                                                         `json:"edgeBlockWebContentOnNewTabPage,omitempty"`
	EdgeBlocked                                           *bool                                                                         `json:"edgeBlocked,omitempty"`
	EdgeClearBrowsingDataOnExit                           *bool                                                                         `json:"edgeClearBrowsingDataOnExit,omitempty"`
	EdgeCookiePolicy                                      *Windows10GeneralConfigurationEdgeCookiePolicy                                `json:"edgeCookiePolicy,omitempty"`
	EdgeDisableFirstRunPage                               *bool                                                                         `json:"edgeDisableFirstRunPage,omitempty"`
	EdgeEnterpriseModeSiteListLocation                    *string                                                                       `json:"edgeEnterpriseModeSiteListLocation,omitempty"`
	EdgeFavoritesBarVisibility                            *Windows10GeneralConfigurationEdgeFavoritesBarVisibility                      `json:"edgeFavoritesBarVisibility,omitempty"`
	EdgeFavoritesListLocation                             *string                                                                       `json:"edgeFavoritesListLocation,omitempty"`
	EdgeFirstRunUrl                                       *string                                                                       `json:"edgeFirstRunUrl,omitempty"`
	EdgeHomeButtonConfiguration                           *EdgeHomeButtonConfiguration                                                  `json:"edgeHomeButtonConfiguration,omitempty"`
	EdgeHomeButtonConfigurationEnabled                    *bool                                                                         `json:"edgeHomeButtonConfigurationEnabled,omitempty"`
	EdgeHomepageUrls                                      *[]string                                                                     `json:"edgeHomepageUrls,omitempty"`
	EdgeKioskModeRestriction                              *Windows10GeneralConfigurationEdgeKioskModeRestriction                        `json:"edgeKioskModeRestriction,omitempty"`
	EdgeKioskResetAfterIdleTimeInMinutes                  *int64                                                                        `json:"edgeKioskResetAfterIdleTimeInMinutes,omitempty"`
	EdgeNewTabPageURL                                     *string                                                                       `json:"edgeNewTabPageURL,omitempty"`
	EdgeOpensWith                                         *Windows10GeneralConfigurationEdgeOpensWith                                   `json:"edgeOpensWith,omitempty"`
	EdgePreventCertificateErrorOverride                   *bool                                                                         `json:"edgePreventCertificateErrorOverride,omitempty"`
	EdgeRequireSmartScreen                                *bool                                                                         `json:"edgeRequireSmartScreen,omitempty"`
	EdgeRequiredExtensionPackageFamilyNames               *[]string                                                                     `json:"edgeRequiredExtensionPackageFamilyNames,omitempty"`
	EdgeSearchEngine                                      *EdgeSearchEngineBase                                                         `json:"edgeSearchEngine,omitempty"`
	EdgeSendIntranetTrafficToInternetExplorer             *bool                                                                         `json:"edgeSendIntranetTrafficToInternetExplorer,omitempty"`
	EdgeShowMessageWhenOpeningInternetExplorerSites       *Windows10GeneralConfigurationEdgeShowMessageWhenOpeningInternetExplorerSites `json:"edgeShowMessageWhenOpeningInternetExplorerSites,omitempty"`
	EdgeSyncFavoritesWithInternetExplorer                 *bool                                                                         `json:"edgeSyncFavoritesWithInternetExplorer,omitempty"`
	EdgeTelemetryForMicrosoft365Analytics                 *Windows10GeneralConfigurationEdgeTelemetryForMicrosoft365Analytics           `json:"edgeTelemetryForMicrosoft365Analytics,omitempty"`
	EnableAutomaticRedeployment                           *bool                                                                         `json:"enableAutomaticRedeployment,omitempty"`
	EnergySaverOnBatteryThresholdPercentage               *int64                                                                        `json:"energySaverOnBatteryThresholdPercentage,omitempty"`
	EnergySaverPluggedInThresholdPercentage               *int64                                                                        `json:"energySaverPluggedInThresholdPercentage,omitempty"`
	EnterpriseCloudPrintDiscoveryEndPoint                 *string                                                                       `json:"enterpriseCloudPrintDiscoveryEndPoint,omitempty"`
	EnterpriseCloudPrintDiscoveryMaxLimit                 *int64                                                                        `json:"enterpriseCloudPrintDiscoveryMaxLimit,omitempty"`
	EnterpriseCloudPrintMopriaDiscoveryResourceIdentifier *string                                                                       `json:"enterpriseCloudPrintMopriaDiscoveryResourceIdentifier,omitempty"`
	EnterpriseCloudPrintOAuthAuthority                    *string                                                                       `json:"enterpriseCloudPrintOAuthAuthority,omitempty"`
	EnterpriseCloudPrintOAuthClientIdentifier             *string                                                                       `json:"enterpriseCloudPrintOAuthClientIdentifier,omitempty"`
	EnterpriseCloudPrintResourceIdentifier                *string                                                                       `json:"enterpriseCloudPrintResourceIdentifier,omitempty"`
	ExperienceBlockDeviceDiscovery                        *bool                                                                         `json:"experienceBlockDeviceDiscovery,omitempty"`
	ExperienceBlockErrorDialogWhenNoSIM                   *bool                                                                         `json:"experienceBlockErrorDialogWhenNoSIM,omitempty"`
	ExperienceBlockTaskSwitcher                           *bool                                                                         `json:"experienceBlockTaskSwitcher,omitempty"`
	ExperienceDoNotSyncBrowserSettings                    *Windows10GeneralConfigurationExperienceDoNotSyncBrowserSettings              `json:"experienceDoNotSyncBrowserSettings,omitempty"`
	FindMyFiles                                           *Windows10GeneralConfigurationFindMyFiles                                     `json:"findMyFiles,omitempty"`
	GameDvrBlocked                                        *bool                                                                         `json:"gameDvrBlocked,omitempty"`
	GroupAssignments                                      *[]DeviceConfigurationGroupAssignment                                         `json:"groupAssignments,omitempty"`
	Id                                                    *string                                                                       `json:"id,omitempty"`
	InkWorkspaceAccess                                    *Windows10GeneralConfigurationInkWorkspaceAccess                              `json:"inkWorkspaceAccess,omitempty"`
	InkWorkspaceAccessState                               *Windows10GeneralConfigurationInkWorkspaceAccessState                         `json:"inkWorkspaceAccessState,omitempty"`
	InkWorkspaceBlockSuggestedApps                        *bool                                                                         `json:"inkWorkspaceBlockSuggestedApps,omitempty"`
	InternetSharingBlocked                                *bool                                                                         `json:"internetSharingBlocked,omitempty"`
	LastModifiedDateTime                                  *string                                                                       `json:"lastModifiedDateTime,omitempty"`
	LocationServicesBlocked                               *bool                                                                         `json:"locationServicesBlocked,omitempty"`
	LockScreenActivateAppsWithVoice                       *Windows10GeneralConfigurationLockScreenActivateAppsWithVoice                 `json:"lockScreenActivateAppsWithVoice,omitempty"`
	LockScreenAllowTimeoutConfiguration                   *bool                                                                         `json:"lockScreenAllowTimeoutConfiguration,omitempty"`
	LockScreenBlockActionCenterNotifications              *bool                                                                         `json:"lockScreenBlockActionCenterNotifications,omitempty"`
	LockScreenBlockCortana                                *bool                                                                         `json:"lockScreenBlockCortana,omitempty"`
	LockScreenBlockToastNotifications                     *bool                                                                         `json:"lockScreenBlockToastNotifications,omitempty"`
	LockScreenTimeoutInSeconds                            *int64                                                                        `json:"lockScreenTimeoutInSeconds,omitempty"`
	LogonBlockFastUserSwitching                           *bool                                                                         `json:"logonBlockFastUserSwitching,omitempty"`
	MessagingBlockMMS                                     *bool                                                                         `json:"messagingBlockMMS,omitempty"`
	MessagingBlockRichCommunicationServices               *bool                                                                         `json:"messagingBlockRichCommunicationServices,omitempty"`
	MessagingBlockSync                                    *bool                                                                         `json:"messagingBlockSync,omitempty"`
	MicrosoftAccountBlockSettingsSync                     *bool                                                                         `json:"microsoftAccountBlockSettingsSync,omitempty"`
	MicrosoftAccountBlocked                               *bool                                                                         `json:"microsoftAccountBlocked,omitempty"`
	MicrosoftAccountSignInAssistantSettings               *Windows10GeneralConfigurationMicrosoftAccountSignInAssistantSettings         `json:"microsoftAccountSignInAssistantSettings,omitempty"`
	NetworkProxyApplySettingsDeviceWide                   *bool                                                                         `json:"networkProxyApplySettingsDeviceWide,omitempty"`
	NetworkProxyAutomaticConfigurationUrl                 *string                                                                       `json:"networkProxyAutomaticConfigurationUrl,omitempty"`
	NetworkProxyDisableAutoDetect                         *bool                                                                         `json:"networkProxyDisableAutoDetect,omitempty"`
	NetworkProxyServer                                    *Windows10NetworkProxyServer                                                  `json:"networkProxyServer,omitempty"`
	NfcBlocked                                            *bool                                                                         `json:"nfcBlocked,omitempty"`
	ODataType                                             *string                                                                       `json:"@odata.type,omitempty"`
	OneDriveDisableFileSync                               *bool                                                                         `json:"oneDriveDisableFileSync,omitempty"`
	PasswordBlockSimple                                   *bool                                                                         `json:"passwordBlockSimple,omitempty"`
	PasswordExpirationDays                                *int64                                                                        `json:"passwordExpirationDays,omitempty"`
	PasswordMinimumAgeInDays                              *int64                                                                        `json:"passwordMinimumAgeInDays,omitempty"`
	PasswordMinimumCharacterSetCount                      *int64                                                                        `json:"passwordMinimumCharacterSetCount,omitempty"`
	PasswordMinimumLength                                 *int64                                                                        `json:"passwordMinimumLength,omitempty"`
	PasswordMinutesOfInactivityBeforeScreenTimeout        *int64                                                                        `json:"passwordMinutesOfInactivityBeforeScreenTimeout,omitempty"`
	PasswordPreviousPasswordBlockCount                    *int64                                                                        `json:"passwordPreviousPasswordBlockCount,omitempty"`
	PasswordRequireWhenResumeFromIdleState                *bool                                                                         `json:"passwordRequireWhenResumeFromIdleState,omitempty"`
	PasswordRequired                                      *bool                                                                         `json:"passwordRequired,omitempty"`
	PasswordRequiredType                                  *Windows10GeneralConfigurationPasswordRequiredType                            `json:"passwordRequiredType,omitempty"`
	PasswordSignInFailureCountBeforeFactoryReset          *int64                                                                        `json:"passwordSignInFailureCountBeforeFactoryReset,omitempty"`
	PersonalizationDesktopImageUrl                        *string                                                                       `json:"personalizationDesktopImageUrl,omitempty"`
	PersonalizationLockScreenImageUrl                     *string                                                                       `json:"personalizationLockScreenImageUrl,omitempty"`
	PowerButtonActionOnBattery                            *Windows10GeneralConfigurationPowerButtonActionOnBattery                      `json:"powerButtonActionOnBattery,omitempty"`
	PowerButtonActionPluggedIn                            *Windows10GeneralConfigurationPowerButtonActionPluggedIn                      `json:"powerButtonActionPluggedIn,omitempty"`
	PowerHybridSleepOnBattery                             *Windows10GeneralConfigurationPowerHybridSleepOnBattery                       `json:"powerHybridSleepOnBattery,omitempty"`
	PowerHybridSleepPluggedIn                             *Windows10GeneralConfigurationPowerHybridSleepPluggedIn                       `json:"powerHybridSleepPluggedIn,omitempty"`
	PowerLidCloseActionOnBattery                          *Windows10GeneralConfigurationPowerLidCloseActionOnBattery                    `json:"powerLidCloseActionOnBattery,omitempty"`
	PowerLidCloseActionPluggedIn                          *Windows10GeneralConfigurationPowerLidCloseActionPluggedIn                    `json:"powerLidCloseActionPluggedIn,omitempty"`
	PowerSleepButtonActionOnBattery                       *Windows10GeneralConfigurationPowerSleepButtonActionOnBattery                 `json:"powerSleepButtonActionOnBattery,omitempty"`
	PowerSleepButtonActionPluggedIn                       *Windows10GeneralConfigurationPowerSleepButtonActionPluggedIn                 `json:"powerSleepButtonActionPluggedIn,omitempty"`
	PrinterBlockAddition                                  *bool                                                                         `json:"printerBlockAddition,omitempty"`
	PrinterDefaultName                                    *string                                                                       `json:"printerDefaultName,omitempty"`
	PrinterNames                                          *[]string                                                                     `json:"printerNames,omitempty"`
	PrivacyAccessControls                                 *[]WindowsPrivacyDataAccessControlItem                                        `json:"privacyAccessControls,omitempty"`
	PrivacyAdvertisingId                                  *Windows10GeneralConfigurationPrivacyAdvertisingId                            `json:"privacyAdvertisingId,omitempty"`
	PrivacyAutoAcceptPairingAndConsentPrompts             *bool                                                                         `json:"privacyAutoAcceptPairingAndConsentPrompts,omitempty"`
	PrivacyBlockActivityFeed                              *bool                                                                         `json:"privacyBlockActivityFeed,omitempty"`
	PrivacyBlockInputPersonalization                      *bool                                                                         `json:"privacyBlockInputPersonalization,omitempty"`
	PrivacyBlockPublishUserActivities                     *bool                                                                         `json:"privacyBlockPublishUserActivities,omitempty"`
	PrivacyDisableLaunchExperience                        *bool                                                                         `json:"privacyDisableLaunchExperience,omitempty"`
	ResetProtectionModeBlocked                            *bool                                                                         `json:"resetProtectionModeBlocked,omitempty"`
	RoleScopeTagIds                                       *[]string                                                                     `json:"roleScopeTagIds,omitempty"`
	SafeSearchFilter                                      *Windows10GeneralConfigurationSafeSearchFilter                                `json:"safeSearchFilter,omitempty"`
	ScreenCaptureBlocked                                  *bool                                                                         `json:"screenCaptureBlocked,omitempty"`
	SearchBlockDiacritics                                 *bool                                                                         `json:"searchBlockDiacritics,omitempty"`
	SearchBlockWebResults                                 *bool                                                                         `json:"searchBlockWebResults,omitempty"`
	SearchDisableAutoLanguageDetection                    *bool                                                                         `json:"searchDisableAutoLanguageDetection,omitempty"`
	SearchDisableIndexerBackoff                           *bool                                                                         `json:"searchDisableIndexerBackoff,omitempty"`
	SearchDisableIndexingEncryptedItems                   *bool                                                                         `json:"searchDisableIndexingEncryptedItems,omitempty"`
	SearchDisableIndexingRemovableDrive                   *bool                                                                         `json:"searchDisableIndexingRemovableDrive,omitempty"`
	SearchDisableLocation                                 *bool                                                                         `json:"searchDisableLocation,omitempty"`
	SearchDisableUseLocation                              *bool                                                                         `json:"searchDisableUseLocation,omitempty"`
	SearchEnableAutomaticIndexSizeManangement             *bool                                                                         `json:"searchEnableAutomaticIndexSizeManangement,omitempty"`
	SearchEnableRemoteQueries                             *bool                                                                         `json:"searchEnableRemoteQueries,omitempty"`
	SecurityBlockAzureADJoinedDevicesAutoEncryption       *bool                                                                         `json:"securityBlockAzureADJoinedDevicesAutoEncryption,omitempty"`
	SettingsBlockAccountsPage                             *bool                                                                         `json:"settingsBlockAccountsPage,omitempty"`
	SettingsBlockAddProvisioningPackage                   *bool                                                                         `json:"settingsBlockAddProvisioningPackage,omitempty"`
	SettingsBlockAppsPage                                 *bool                                                                         `json:"settingsBlockAppsPage,omitempty"`
	SettingsBlockChangeLanguage                           *bool                                                                         `json:"settingsBlockChangeLanguage,omitempty"`
	SettingsBlockChangePowerSleep                         *bool                                                                         `json:"settingsBlockChangePowerSleep,omitempty"`
	SettingsBlockChangeRegion                             *bool                                                                         `json:"settingsBlockChangeRegion,omitempty"`
	SettingsBlockChangeSystemTime                         *bool                                                                         `json:"settingsBlockChangeSystemTime,omitempty"`
	SettingsBlockDevicesPage                              *bool                                                                         `json:"settingsBlockDevicesPage,omitempty"`
	SettingsBlockEaseOfAccessPage                         *bool                                                                         `json:"settingsBlockEaseOfAccessPage,omitempty"`
	SettingsBlockEditDeviceName                           *bool                                                                         `json:"settingsBlockEditDeviceName,omitempty"`
	SettingsBlockGamingPage                               *bool                                                                         `json:"settingsBlockGamingPage,omitempty"`
	SettingsBlockNetworkInternetPage                      *bool                                                                         `json:"settingsBlockNetworkInternetPage,omitempty"`
	SettingsBlockPersonalizationPage                      *bool                                                                         `json:"settingsBlockPersonalizationPage,omitempty"`
	SettingsBlockPrivacyPage                              *bool                                                                         `json:"settingsBlockPrivacyPage,omitempty"`
	SettingsBlockRemoveProvisioningPackage                *bool                                                                         `json:"settingsBlockRemoveProvisioningPackage,omitempty"`
	SettingsBlockSettingsApp                              *bool                                                                         `json:"settingsBlockSettingsApp,omitempty"`
	SettingsBlockSystemPage                               *bool                                                                         `json:"settingsBlockSystemPage,omitempty"`
	SettingsBlockTimeLanguagePage                         *bool                                                                         `json:"settingsBlockTimeLanguagePage,omitempty"`
	SettingsBlockUpdateSecurityPage                       *bool                                                                         `json:"settingsBlockUpdateSecurityPage,omitempty"`
	SharedUserAppDataAllowed                              *bool                                                                         `json:"sharedUserAppDataAllowed,omitempty"`
	SmartScreenAppInstallControl                          *Windows10GeneralConfigurationSmartScreenAppInstallControl                    `json:"smartScreenAppInstallControl,omitempty"`
	SmartScreenBlockPromptOverride                        *bool                                                                         `json:"smartScreenBlockPromptOverride,omitempty"`
	SmartScreenBlockPromptOverrideForFiles                *bool                                                                         `json:"smartScreenBlockPromptOverrideForFiles,omitempty"`
	SmartScreenEnableAppInstallControl                    *bool                                                                         `json:"smartScreenEnableAppInstallControl,omitempty"`
	StartBlockUnpinningAppsFromTaskbar                    *bool                                                                         `json:"startBlockUnpinningAppsFromTaskbar,omitempty"`
	StartMenuAppListVisibility                            *Windows10GeneralConfigurationStartMenuAppListVisibility                      `json:"startMenuAppListVisibility,omitempty"`
	StartMenuHideChangeAccountSettings                    *bool                                                                         `json:"startMenuHideChangeAccountSettings,omitempty"`
	StartMenuHideFrequentlyUsedApps                       *bool                                                                         `json:"startMenuHideFrequentlyUsedApps,omitempty"`
	StartMenuHideHibernate                                *bool                                                                         `json:"startMenuHideHibernate,omitempty"`
	StartMenuHideLock                                     *bool                                                                         `json:"startMenuHideLock,omitempty"`
	StartMenuHidePowerButton                              *bool                                                                         `json:"startMenuHidePowerButton,omitempty"`
	StartMenuHideRecentJumpLists                          *bool                                                                         `json:"startMenuHideRecentJumpLists,omitempty"`
	StartMenuHideRecentlyAddedApps                        *bool                                                                         `json:"startMenuHideRecentlyAddedApps,omitempty"`
	StartMenuHideRestartOptions                           *bool                                                                         `json:"startMenuHideRestartOptions,omitempty"`
	StartMenuHideShutDown                                 *bool                                                                         `json:"startMenuHideShutDown,omitempty"`
	StartMenuHideSignOut                                  *bool                                                                         `json:"startMenuHideSignOut,omitempty"`
	StartMenuHideSleep                                    *bool                                                                         `json:"startMenuHideSleep,omitempty"`
	StartMenuHideSwitchAccount                            *bool                                                                         `json:"startMenuHideSwitchAccount,omitempty"`
	StartMenuHideUserTile                                 *bool                                                                         `json:"startMenuHideUserTile,omitempty"`
	StartMenuLayoutEdgeAssetsXml                          *string                                                                       `json:"startMenuLayoutEdgeAssetsXml,omitempty"`
	StartMenuLayoutXml                                    *string                                                                       `json:"startMenuLayoutXml,omitempty"`
	StartMenuMode                                         *Windows10GeneralConfigurationStartMenuMode                                   `json:"startMenuMode,omitempty"`
	StartMenuPinnedFolderDocuments                        *Windows10GeneralConfigurationStartMenuPinnedFolderDocuments                  `json:"startMenuPinnedFolderDocuments,omitempty"`
	StartMenuPinnedFolderDownloads                        *Windows10GeneralConfigurationStartMenuPinnedFolderDownloads                  `json:"startMenuPinnedFolderDownloads,omitempty"`
	StartMenuPinnedFolderFileExplorer                     *Windows10GeneralConfigurationStartMenuPinnedFolderFileExplorer               `json:"startMenuPinnedFolderFileExplorer,omitempty"`
	StartMenuPinnedFolderHomeGroup                        *Windows10GeneralConfigurationStartMenuPinnedFolderHomeGroup                  `json:"startMenuPinnedFolderHomeGroup,omitempty"`
	StartMenuPinnedFolderMusic                            *Windows10GeneralConfigurationStartMenuPinnedFolderMusic                      `json:"startMenuPinnedFolderMusic,omitempty"`
	StartMenuPinnedFolderNetwork                          *Windows10GeneralConfigurationStartMenuPinnedFolderNetwork                    `json:"startMenuPinnedFolderNetwork,omitempty"`
	StartMenuPinnedFolderPersonalFolder                   *Windows10GeneralConfigurationStartMenuPinnedFolderPersonalFolder             `json:"startMenuPinnedFolderPersonalFolder,omitempty"`
	StartMenuPinnedFolderPictures                         *Windows10GeneralConfigurationStartMenuPinnedFolderPictures                   `json:"startMenuPinnedFolderPictures,omitempty"`
	StartMenuPinnedFolderSettings                         *Windows10GeneralConfigurationStartMenuPinnedFolderSettings                   `json:"startMenuPinnedFolderSettings,omitempty"`
	StartMenuPinnedFolderVideos                           *Windows10GeneralConfigurationStartMenuPinnedFolderVideos                     `json:"startMenuPinnedFolderVideos,omitempty"`
	StorageBlockRemovableStorage                          *bool                                                                         `json:"storageBlockRemovableStorage,omitempty"`
	StorageRequireMobileDeviceEncryption                  *bool                                                                         `json:"storageRequireMobileDeviceEncryption,omitempty"`
	StorageRestrictAppDataToSystemVolume                  *bool                                                                         `json:"storageRestrictAppDataToSystemVolume,omitempty"`
	StorageRestrictAppInstallToSystemVolume               *bool                                                                         `json:"storageRestrictAppInstallToSystemVolume,omitempty"`
	SupportsScopeTags                                     *bool                                                                         `json:"supportsScopeTags,omitempty"`
	SystemTelemetryProxyServer                            *string                                                                       `json:"systemTelemetryProxyServer,omitempty"`
	TaskManagerBlockEndTask                               *bool                                                                         `json:"taskManagerBlockEndTask,omitempty"`
	TenantLockdownRequireNetworkDuringOutOfBoxExperience  *bool                                                                         `json:"tenantLockdownRequireNetworkDuringOutOfBoxExperience,omitempty"`
	UninstallBuiltInApps                                  *bool                                                                         `json:"uninstallBuiltInApps,omitempty"`
	UsbBlocked                                            *bool                                                                         `json:"usbBlocked,omitempty"`
	UserStatusOverview                                    *DeviceConfigurationUserOverview                                              `json:"userStatusOverview,omitempty"`
	UserStatuses                                          *[]DeviceConfigurationUserStatus                                              `json:"userStatuses,omitempty"`
	Version                                               *int64                                                                        `json:"version,omitempty"`
	VoiceRecordingBlocked                                 *bool                                                                         `json:"voiceRecordingBlocked,omitempty"`
	WebRtcBlockLocalhostIpAddress                         *bool                                                                         `json:"webRtcBlockLocalhostIpAddress,omitempty"`
	WiFiBlockAutomaticConnectHotspots                     *bool                                                                         `json:"wiFiBlockAutomaticConnectHotspots,omitempty"`
	WiFiBlockManualConfiguration                          *bool                                                                         `json:"wiFiBlockManualConfiguration,omitempty"`
	WiFiBlocked                                           *bool                                                                         `json:"wiFiBlocked,omitempty"`
	WiFiScanInterval                                      *int64                                                                        `json:"wiFiScanInterval,omitempty"`
	Windows10AppsForceUpdateSchedule                      *Windows10AppsForceUpdateSchedule                                             `json:"windows10AppsForceUpdateSchedule,omitempty"`
	WindowsSpotlightBlockConsumerSpecificFeatures         *bool                                                                         `json:"windowsSpotlightBlockConsumerSpecificFeatures,omitempty"`
	WindowsSpotlightBlockOnActionCenter                   *bool                                                                         `json:"windowsSpotlightBlockOnActionCenter,omitempty"`
	WindowsSpotlightBlockTailoredExperiences              *bool                                                                         `json:"windowsSpotlightBlockTailoredExperiences,omitempty"`
	WindowsSpotlightBlockThirdPartyNotifications          *bool                                                                         `json:"windowsSpotlightBlockThirdPartyNotifications,omitempty"`
	WindowsSpotlightBlockWelcomeExperience                *bool                                                                         `json:"windowsSpotlightBlockWelcomeExperience,omitempty"`
	WindowsSpotlightBlockWindowsTips                      *bool                                                                         `json:"windowsSpotlightBlockWindowsTips,omitempty"`
	WindowsSpotlightBlocked                               *bool                                                                         `json:"windowsSpotlightBlocked,omitempty"`
	WindowsSpotlightConfigureOnLockScreen                 *Windows10GeneralConfigurationWindowsSpotlightConfigureOnLockScreen           `json:"windowsSpotlightConfigureOnLockScreen,omitempty"`
	WindowsStoreBlockAutoUpdate                           *bool                                                                         `json:"windowsStoreBlockAutoUpdate,omitempty"`
	WindowsStoreBlocked                                   *bool                                                                         `json:"windowsStoreBlocked,omitempty"`
	WindowsStoreEnablePrivateStoreOnly                    *bool                                                                         `json:"windowsStoreEnablePrivateStoreOnly,omitempty"`
	WirelessDisplayBlockProjectionToThisDevice            *bool                                                                         `json:"wirelessDisplayBlockProjectionToThisDevice,omitempty"`
	WirelessDisplayBlockUserInputFromReceiver             *bool                                                                         `json:"wirelessDisplayBlockUserInputFromReceiver,omitempty"`
	WirelessDisplayRequirePinForPairing                   *bool                                                                         `json:"wirelessDisplayRequirePinForPairing,omitempty"`
}
