package beta

// Copyright (c) HashiCorp Inc. All rights reserved.
// Licensed under the MIT License. See NOTICE.txt in the project root for license information.

type User struct {
	AboutMe                                         *string                                           `json:"aboutMe,omitempty"`
	AccountEnabled                                  *bool                                             `json:"accountEnabled,omitempty"`
	Activities                                      *[]UserActivity                                   `json:"activities,omitempty"`
	AgeGroup                                        *string                                           `json:"ageGroup,omitempty"`
	AgreementAcceptances                            *[]AgreementAcceptance                            `json:"agreementAcceptances,omitempty"`
	Analytics                                       *UserAnalytics                                    `json:"analytics,omitempty"`
	AppConsentRequestsForApproval                   *[]AppConsentRequest                              `json:"appConsentRequestsForApproval,omitempty"`
	AppRoleAssignedResources                        *[]ServicePrincipal                               `json:"appRoleAssignedResources,omitempty"`
	AppRoleAssignments                              *[]AppRoleAssignment                              `json:"appRoleAssignments,omitempty"`
	Approvals                                       *[]Approval                                       `json:"approvals,omitempty"`
	AssignedLicenses                                *[]AssignedLicense                                `json:"assignedLicenses,omitempty"`
	AssignedPlans                                   *[]AssignedPlan                                   `json:"assignedPlans,omitempty"`
	Authentication                                  *Authentication                                   `json:"authentication,omitempty"`
	AuthorizationInfo                               *AuthorizationInfo                                `json:"authorizationInfo,omitempty"`
	Birthday                                        *string                                           `json:"birthday,omitempty"`
	BusinessPhones                                  *[]string                                         `json:"businessPhones,omitempty"`
	Calendar                                        *Calendar                                         `json:"calendar,omitempty"`
	CalendarGroups                                  *[]CalendarGroup                                  `json:"calendarGroups,omitempty"`
	CalendarView                                    *[]Event                                          `json:"calendarView,omitempty"`
	Calendars                                       *[]Calendar                                       `json:"calendars,omitempty"`
	Chats                                           *[]Chat                                           `json:"chats,omitempty"`
	City                                            *string                                           `json:"city,omitempty"`
	CloudPCs                                        *[]CloudPC                                        `json:"cloudPCs,omitempty"`
	CloudRealtimeCommunicationInfo                  *CloudRealtimeCommunicationInfo                   `json:"cloudRealtimeCommunicationInfo,omitempty"`
	CompanyName                                     *string                                           `json:"companyName,omitempty"`
	ConsentProvidedForMinor                         *string                                           `json:"consentProvidedForMinor,omitempty"`
	ContactFolders                                  *[]ContactFolder                                  `json:"contactFolders,omitempty"`
	Contacts                                        *[]Contact                                        `json:"contacts,omitempty"`
	Country                                         *string                                           `json:"country,omitempty"`
	CreatedDateTime                                 *string                                           `json:"createdDateTime,omitempty"`
	CreatedObjects                                  *[]DirectoryObject                                `json:"createdObjects,omitempty"`
	CreationType                                    *string                                           `json:"creationType,omitempty"`
	CustomSecurityAttributes                        *CustomSecurityAttributeValue                     `json:"customSecurityAttributes,omitempty"`
	DeletedDateTime                                 *string                                           `json:"deletedDateTime,omitempty"`
	Department                                      *string                                           `json:"department,omitempty"`
	DeviceEnrollmentConfigurations                  *[]DeviceEnrollmentConfiguration                  `json:"deviceEnrollmentConfigurations,omitempty"`
	DeviceEnrollmentLimit                           *int64                                            `json:"deviceEnrollmentLimit,omitempty"`
	DeviceKeys                                      *[]DeviceKey                                      `json:"deviceKeys,omitempty"`
	DeviceManagementTroubleshootingEvents           *[]DeviceManagementTroubleshootingEvent           `json:"deviceManagementTroubleshootingEvents,omitempty"`
	Devices                                         *[]Device                                         `json:"devices,omitempty"`
	DirectReports                                   *[]DirectoryObject                                `json:"directReports,omitempty"`
	DisplayName                                     *string                                           `json:"displayName,omitempty"`
	Drive                                           *Drive                                            `json:"drive,omitempty"`
	Drives                                          *[]Drive                                          `json:"drives,omitempty"`
	EmployeeExperience                              *EmployeeExperienceUser                           `json:"employeeExperience,omitempty"`
	EmployeeHireDate                                *string                                           `json:"employeeHireDate,omitempty"`
	EmployeeId                                      *string                                           `json:"employeeId,omitempty"`
	EmployeeLeaveDateTime                           *string                                           `json:"employeeLeaveDateTime,omitempty"`
	EmployeeOrgData                                 *EmployeeOrgData                                  `json:"employeeOrgData,omitempty"`
	EmployeeType                                    *string                                           `json:"employeeType,omitempty"`
	Events                                          *[]Event                                          `json:"events,omitempty"`
	Extensions                                      *[]Extension                                      `json:"extensions,omitempty"`
	ExternalUserState                               *string                                           `json:"externalUserState,omitempty"`
	ExternalUserStateChangeDateTime                 *string                                           `json:"externalUserStateChangeDateTime,omitempty"`
	FaxNumber                                       *string                                           `json:"faxNumber,omitempty"`
	FollowedSites                                   *[]Site                                           `json:"followedSites,omitempty"`
	GivenName                                       *string                                           `json:"givenName,omitempty"`
	HireDate                                        *string                                           `json:"hireDate,omitempty"`
	Id                                              *string                                           `json:"id,omitempty"`
	Identities                                      *[]ObjectIdentity                                 `json:"identities,omitempty"`
	ImAddresses                                     *[]string                                         `json:"imAddresses,omitempty"`
	InferenceClassification                         *InferenceClassification                          `json:"inferenceClassification,omitempty"`
	InfoCatalogs                                    *[]string                                         `json:"infoCatalogs,omitempty"`
	InformationProtection                           *InformationProtection                            `json:"informationProtection,omitempty"`
	Insights                                        *ItemInsights                                     `json:"insights,omitempty"`
	Interests                                       *[]string                                         `json:"interests,omitempty"`
	IsLicenseReconciliationNeeded                   *bool                                             `json:"isLicenseReconciliationNeeded,omitempty"`
	IsManagementRestricted                          *bool                                             `json:"isManagementRestricted,omitempty"`
	IsResourceAccount                               *bool                                             `json:"isResourceAccount,omitempty"`
	JobTitle                                        *string                                           `json:"jobTitle,omitempty"`
	JoinedGroups                                    *[]Group                                          `json:"joinedGroups,omitempty"`
	JoinedTeams                                     *[]Team                                           `json:"joinedTeams,omitempty"`
	LastPasswordChangeDateTime                      *string                                           `json:"lastPasswordChangeDateTime,omitempty"`
	LegalAgeGroupClassification                     *string                                           `json:"legalAgeGroupClassification,omitempty"`
	LicenseAssignmentStates                         *[]LicenseAssignmentState                         `json:"licenseAssignmentStates,omitempty"`
	LicenseDetails                                  *[]LicenseDetails                                 `json:"licenseDetails,omitempty"`
	Mail                                            *string                                           `json:"mail,omitempty"`
	MailFolders                                     *[]MailFolder                                     `json:"mailFolders,omitempty"`
	MailNickname                                    *string                                           `json:"mailNickname,omitempty"`
	MailboxSettings                                 *MailboxSettings                                  `json:"mailboxSettings,omitempty"`
	ManagedAppRegistrations                         *[]ManagedAppRegistration                         `json:"managedAppRegistrations,omitempty"`
	ManagedDevices                                  *[]ManagedDevice                                  `json:"managedDevices,omitempty"`
	Manager                                         *DirectoryObject                                  `json:"manager,omitempty"`
	MemberOf                                        *[]DirectoryObject                                `json:"memberOf,omitempty"`
	Messages                                        *[]Message                                        `json:"messages,omitempty"`
	MobileAppIntentAndStates                        *[]MobileAppIntentAndState                        `json:"mobileAppIntentAndStates,omitempty"`
	MobileAppTroubleshootingEvents                  *[]MobileAppTroubleshootingEvent                  `json:"mobileAppTroubleshootingEvents,omitempty"`
	MobilePhone                                     *string                                           `json:"mobilePhone,omitempty"`
	MySite                                          *string                                           `json:"mySite,omitempty"`
	Notifications                                   *[]Notification                                   `json:"notifications,omitempty"`
	ODataType                                       *string                                           `json:"@odata.type,omitempty"`
	Oauth2PermissionGrants                          *[]OAuth2PermissionGrant                          `json:"oauth2PermissionGrants,omitempty"`
	OfficeLocation                                  *string                                           `json:"officeLocation,omitempty"`
	OnPremisesDistinguishedName                     *string                                           `json:"onPremisesDistinguishedName,omitempty"`
	OnPremisesDomainName                            *string                                           `json:"onPremisesDomainName,omitempty"`
	OnPremisesExtensionAttributes                   *OnPremisesExtensionAttributes                    `json:"onPremisesExtensionAttributes,omitempty"`
	OnPremisesImmutableId                           *string                                           `json:"onPremisesImmutableId,omitempty"`
	OnPremisesLastSyncDateTime                      *string                                           `json:"onPremisesLastSyncDateTime,omitempty"`
	OnPremisesProvisioningErrors                    *[]OnPremisesProvisioningError                    `json:"onPremisesProvisioningErrors,omitempty"`
	OnPremisesSamAccountName                        *string                                           `json:"onPremisesSamAccountName,omitempty"`
	OnPremisesSecurityIdentifier                    *string                                           `json:"onPremisesSecurityIdentifier,omitempty"`
	OnPremisesSipInfo                               *OnPremisesSipInfo                                `json:"onPremisesSipInfo,omitempty"`
	OnPremisesSyncEnabled                           *bool                                             `json:"onPremisesSyncEnabled,omitempty"`
	OnPremisesUserPrincipalName                     *string                                           `json:"onPremisesUserPrincipalName,omitempty"`
	Onenote                                         *Onenote                                          `json:"onenote,omitempty"`
	OnlineMeetings                                  *[]OnlineMeeting                                  `json:"onlineMeetings,omitempty"`
	OtherMails                                      *[]string                                         `json:"otherMails,omitempty"`
	Outlook                                         *OutlookUser                                      `json:"outlook,omitempty"`
	OwnedDevices                                    *[]DirectoryObject                                `json:"ownedDevices,omitempty"`
	OwnedObjects                                    *[]DirectoryObject                                `json:"ownedObjects,omitempty"`
	PasswordPolicies                                *string                                           `json:"passwordPolicies,omitempty"`
	PasswordProfile                                 *PasswordProfile                                  `json:"passwordProfile,omitempty"`
	PastProjects                                    *[]string                                         `json:"pastProjects,omitempty"`
	PendingAccessReviewInstances                    *[]AccessReviewInstance                           `json:"pendingAccessReviewInstances,omitempty"`
	People                                          *[]Person                                         `json:"people,omitempty"`
	PermissionGrants                                *[]ResourceSpecificPermissionGrant                `json:"permissionGrants,omitempty"`
	Photo                                           *ProfilePhoto                                     `json:"photo,omitempty"`
	Photos                                          *[]ProfilePhoto                                   `json:"photos,omitempty"`
	Planner                                         *PlannerUser                                      `json:"planner,omitempty"`
	PostalCode                                      *string                                           `json:"postalCode,omitempty"`
	PreferredDataLocation                           *string                                           `json:"preferredDataLocation,omitempty"`
	PreferredLanguage                               *string                                           `json:"preferredLanguage,omitempty"`
	PreferredName                                   *string                                           `json:"preferredName,omitempty"`
	Presence                                        *Presence                                         `json:"presence,omitempty"`
	Print                                           *UserPrint                                        `json:"print,omitempty"`
	Profile                                         *Profile                                          `json:"profile,omitempty"`
	ProvisionedPlans                                *[]ProvisionedPlan                                `json:"provisionedPlans,omitempty"`
	ProxyAddresses                                  *[]string                                         `json:"proxyAddresses,omitempty"`
	RefreshTokensValidFromDateTime                  *string                                           `json:"refreshTokensValidFromDateTime,omitempty"`
	RegisteredDevices                               *[]DirectoryObject                                `json:"registeredDevices,omitempty"`
	Responsibilities                                *[]string                                         `json:"responsibilities,omitempty"`
	Schools                                         *[]string                                         `json:"schools,omitempty"`
	ScopedRoleMemberOf                              *[]ScopedRoleMembership                           `json:"scopedRoleMemberOf,omitempty"`
	Security                                        *SecuritySecurity                                 `json:"security,omitempty"`
	SecurityIdentifier                              *string                                           `json:"securityIdentifier,omitempty"`
	ServiceProvisioningErrors                       *[]ServiceProvisioningError                       `json:"serviceProvisioningErrors,omitempty"`
	Settings                                        *UserSettings                                     `json:"settings,omitempty"`
	ShowInAddressList                               *bool                                             `json:"showInAddressList,omitempty"`
	SignInActivity                                  *SignInActivity                                   `json:"signInActivity,omitempty"`
	SignInSessionsValidFromDateTime                 *string                                           `json:"signInSessionsValidFromDateTime,omitempty"`
	Skills                                          *[]string                                         `json:"skills,omitempty"`
	Sponsors                                        *[]DirectoryObject                                `json:"sponsors,omitempty"`
	State                                           *string                                           `json:"state,omitempty"`
	StreetAddress                                   *string                                           `json:"streetAddress,omitempty"`
	Surname                                         *string                                           `json:"surname,omitempty"`
	Teamwork                                        *UserTeamwork                                     `json:"teamwork,omitempty"`
	Todo                                            *Todo                                             `json:"todo,omitempty"`
	TransitiveMemberOf                              *[]DirectoryObject                                `json:"transitiveMemberOf,omitempty"`
	TransitiveReports                               *[]DirectoryObject                                `json:"transitiveReports,omitempty"`
	UsageLocation                                   *string                                           `json:"usageLocation,omitempty"`
	UsageRights                                     *[]UsageRight                                     `json:"usageRights,omitempty"`
	UserPrincipalName                               *string                                           `json:"userPrincipalName,omitempty"`
	UserType                                        *string                                           `json:"userType,omitempty"`
	VirtualEvents                                   *UserVirtualEventsRoot                            `json:"virtualEvents,omitempty"`
	WindowsInformationProtectionDeviceRegistrations *[]WindowsInformationProtectionDeviceRegistration `json:"windowsInformationProtectionDeviceRegistrations,omitempty"`
}
