package beta

// Copyright (c) HashiCorp Inc. All rights reserved.
// Licensed under the MIT License. See NOTICE.txt in the project root for license information.

type IosikEv2VpnConfiguration struct {
	AllowDefaultChildSecurityAssociationParameters *bool                                             `json:"allowDefaultChildSecurityAssociationParameters,omitempty"`
	AllowDefaultSecurityAssociationParameters      *bool                                             `json:"allowDefaultSecurityAssociationParameters,omitempty"`
	AlwaysOnConfiguration                          *AppleVpnAlwaysOnConfiguration                    `json:"alwaysOnConfiguration,omitempty"`
	Assignments                                    *[]DeviceConfigurationAssignment                  `json:"assignments,omitempty"`
	AssociatedDomains                              *[]string                                         `json:"associatedDomains,omitempty"`
	AuthenticationMethod                           *IosikEv2VpnConfigurationAuthenticationMethod     `json:"authenticationMethod,omitempty"`
	ChildSecurityAssociationParameters             *IosVpnSecurityAssociationParameters              `json:"childSecurityAssociationParameters,omitempty"`
	ClientAuthenticationType                       *IosikEv2VpnConfigurationClientAuthenticationType `json:"clientAuthenticationType,omitempty"`
	CloudName                                      *string                                           `json:"cloudName,omitempty"`
	ConnectionName                                 *string                                           `json:"connectionName,omitempty"`
	ConnectionType                                 *IosikEv2VpnConfigurationConnectionType           `json:"connectionType,omitempty"`
	CreatedDateTime                                *string                                           `json:"createdDateTime,omitempty"`
	CustomData                                     *[]KeyValue                                       `json:"customData,omitempty"`
	CustomKeyValueData                             *[]KeyValuePair                                   `json:"customKeyValueData,omitempty"`
	DeadPeerDetectionRate                          *IosikEv2VpnConfigurationDeadPeerDetectionRate    `json:"deadPeerDetectionRate,omitempty"`
	DerivedCredentialSettings                      *DeviceManagementDerivedCredentialSettings        `json:"derivedCredentialSettings,omitempty"`
	Description                                    *string                                           `json:"description,omitempty"`
	DeviceManagementApplicabilityRuleDeviceMode    *DeviceManagementApplicabilityRuleDeviceMode      `json:"deviceManagementApplicabilityRuleDeviceMode,omitempty"`
	DeviceManagementApplicabilityRuleOsEdition     *DeviceManagementApplicabilityRuleOsEdition       `json:"deviceManagementApplicabilityRuleOsEdition,omitempty"`
	DeviceManagementApplicabilityRuleOsVersion     *DeviceManagementApplicabilityRuleOsVersion       `json:"deviceManagementApplicabilityRuleOsVersion,omitempty"`
	DeviceSettingStateSummaries                    *[]SettingStateDeviceSummary                      `json:"deviceSettingStateSummaries,omitempty"`
	DeviceStatusOverview                           *DeviceConfigurationDeviceOverview                `json:"deviceStatusOverview,omitempty"`
	DeviceStatuses                                 *[]DeviceConfigurationDeviceStatus                `json:"deviceStatuses,omitempty"`
	DisableMobilityAndMultihoming                  *bool                                             `json:"disableMobilityAndMultihoming,omitempty"`
	DisableOnDemandUserOverride                    *bool                                             `json:"disableOnDemandUserOverride,omitempty"`
	DisableRedirect                                *bool                                             `json:"disableRedirect,omitempty"`
	DisconnectOnIdle                               *bool                                             `json:"disconnectOnIdle,omitempty"`
	DisconnectOnIdleTimerInSeconds                 *int64                                            `json:"disconnectOnIdleTimerInSeconds,omitempty"`
	DisplayName                                    *string                                           `json:"displayName,omitempty"`
	EnableAlwaysOnConfiguration                    *bool                                             `json:"enableAlwaysOnConfiguration,omitempty"`
	EnableCertificateRevocationCheck               *bool                                             `json:"enableCertificateRevocationCheck,omitempty"`
	EnableEAP                                      *bool                                             `json:"enableEAP,omitempty"`
	EnablePerApp                                   *bool                                             `json:"enablePerApp,omitempty"`
	EnablePerfectForwardSecrecy                    *bool                                             `json:"enablePerfectForwardSecrecy,omitempty"`
	EnableSplitTunneling                           *bool                                             `json:"enableSplitTunneling,omitempty"`
	EnableUseInternalSubnetAttributes              *bool                                             `json:"enableUseInternalSubnetAttributes,omitempty"`
	ExcludeList                                    *[]string                                         `json:"excludeList,omitempty"`
	ExcludedDomains                                *[]string                                         `json:"excludedDomains,omitempty"`
	GroupAssignments                               *[]DeviceConfigurationGroupAssignment             `json:"groupAssignments,omitempty"`
	Id                                             *string                                           `json:"id,omitempty"`
	Identifier                                     *string                                           `json:"identifier,omitempty"`
	IdentityCertificate                            *IosCertificateProfileBase                        `json:"identityCertificate,omitempty"`
	LastModifiedDateTime                           *string                                           `json:"lastModifiedDateTime,omitempty"`
	LocalIdentifier                                *IosikEv2VpnConfigurationLocalIdentifier          `json:"localIdentifier,omitempty"`
	LoginGroupOrDomain                             *string                                           `json:"loginGroupOrDomain,omitempty"`
	MicrosoftTunnelSiteId                          *string                                           `json:"microsoftTunnelSiteId,omitempty"`
	MtuSizeInBytes                                 *int64                                            `json:"mtuSizeInBytes,omitempty"`
	ODataType                                      *string                                           `json:"@odata.type,omitempty"`
	OnDemandRules                                  *[]VpnOnDemandRule                                `json:"onDemandRules,omitempty"`
	OptInToDeviceIdSharing                         *bool                                             `json:"optInToDeviceIdSharing,omitempty"`
	ProviderType                                   *IosikEv2VpnConfigurationProviderType             `json:"providerType,omitempty"`
	ProxyServer                                    *VpnProxyServer                                   `json:"proxyServer,omitempty"`
	Realm                                          *string                                           `json:"realm,omitempty"`
	RemoteIdentifier                               *string                                           `json:"remoteIdentifier,omitempty"`
	Role                                           *string                                           `json:"role,omitempty"`
	RoleScopeTagIds                                *[]string                                         `json:"roleScopeTagIds,omitempty"`
	SafariDomains                                  *[]string                                         `json:"safariDomains,omitempty"`
	SecurityAssociationParameters                  *IosVpnSecurityAssociationParameters              `json:"securityAssociationParameters,omitempty"`
	Server                                         *VpnServer                                        `json:"server,omitempty"`
	ServerCertificateCommonName                    *string                                           `json:"serverCertificateCommonName,omitempty"`
	ServerCertificateIssuerCommonName              *string                                           `json:"serverCertificateIssuerCommonName,omitempty"`
	ServerCertificateType                          *IosikEv2VpnConfigurationServerCertificateType    `json:"serverCertificateType,omitempty"`
	SharedSecret                                   *string                                           `json:"sharedSecret,omitempty"`
	StrictEnforcement                              *bool                                             `json:"strictEnforcement,omitempty"`
	SupportsScopeTags                              *bool                                             `json:"supportsScopeTags,omitempty"`
	TargetedMobileApps                             *[]AppListItem                                    `json:"targetedMobileApps,omitempty"`
	TlsMaximumVersion                              *string                                           `json:"tlsMaximumVersion,omitempty"`
	TlsMinimumVersion                              *string                                           `json:"tlsMinimumVersion,omitempty"`
	UserDomain                                     *string                                           `json:"userDomain,omitempty"`
	UserStatusOverview                             *DeviceConfigurationUserOverview                  `json:"userStatusOverview,omitempty"`
	UserStatuses                                   *[]DeviceConfigurationUserStatus                  `json:"userStatuses,omitempty"`
	Version                                        *int64                                            `json:"version,omitempty"`
}
