package beta

// Copyright (c) HashiCorp Inc. All rights reserved.
// Licensed under the MIT License. See NOTICE.txt in the project root for license information.

type MacOSGeneralDeviceConfiguration struct {
	ActivationLockWhenSupervisedAllowed             *bool                                                `json:"activationLockWhenSupervisedAllowed,omitempty"`
	AddingGameCenterFriendsBlocked                  *bool                                                `json:"addingGameCenterFriendsBlocked,omitempty"`
	AirDropBlocked                                  *bool                                                `json:"airDropBlocked,omitempty"`
	AppleWatchBlockAutoUnlock                       *bool                                                `json:"appleWatchBlockAutoUnlock,omitempty"`
	Assignments                                     *[]DeviceConfigurationAssignment                     `json:"assignments,omitempty"`
	CameraBlocked                                   *bool                                                `json:"cameraBlocked,omitempty"`
	ClassroomAppBlockRemoteScreenObservation        *bool                                                `json:"classroomAppBlockRemoteScreenObservation,omitempty"`
	ClassroomAppForceUnpromptedScreenObservation    *bool                                                `json:"classroomAppForceUnpromptedScreenObservation,omitempty"`
	ClassroomForceAutomaticallyJoinClasses          *bool                                                `json:"classroomForceAutomaticallyJoinClasses,omitempty"`
	ClassroomForceRequestPermissionToLeaveClasses   *bool                                                `json:"classroomForceRequestPermissionToLeaveClasses,omitempty"`
	ClassroomForceUnpromptedAppAndDeviceLock        *bool                                                `json:"classroomForceUnpromptedAppAndDeviceLock,omitempty"`
	CompliantAppListType                            *MacOSGeneralDeviceConfigurationCompliantAppListType `json:"compliantAppListType,omitempty"`
	CompliantAppsList                               *[]AppListItem                                       `json:"compliantAppsList,omitempty"`
	ContentCachingBlocked                           *bool                                                `json:"contentCachingBlocked,omitempty"`
	CreatedDateTime                                 *string                                              `json:"createdDateTime,omitempty"`
	DefinitionLookupBlocked                         *bool                                                `json:"definitionLookupBlocked,omitempty"`
	Description                                     *string                                              `json:"description,omitempty"`
	DeviceManagementApplicabilityRuleDeviceMode     *DeviceManagementApplicabilityRuleDeviceMode         `json:"deviceManagementApplicabilityRuleDeviceMode,omitempty"`
	DeviceManagementApplicabilityRuleOsEdition      *DeviceManagementApplicabilityRuleOsEdition          `json:"deviceManagementApplicabilityRuleOsEdition,omitempty"`
	DeviceManagementApplicabilityRuleOsVersion      *DeviceManagementApplicabilityRuleOsVersion          `json:"deviceManagementApplicabilityRuleOsVersion,omitempty"`
	DeviceSettingStateSummaries                     *[]SettingStateDeviceSummary                         `json:"deviceSettingStateSummaries,omitempty"`
	DeviceStatusOverview                            *DeviceConfigurationDeviceOverview                   `json:"deviceStatusOverview,omitempty"`
	DeviceStatuses                                  *[]DeviceConfigurationDeviceStatus                   `json:"deviceStatuses,omitempty"`
	DisplayName                                     *string                                              `json:"displayName,omitempty"`
	EmailInDomainSuffixes                           *[]string                                            `json:"emailInDomainSuffixes,omitempty"`
	EraseContentAndSettingsBlocked                  *bool                                                `json:"eraseContentAndSettingsBlocked,omitempty"`
	GameCenterBlocked                               *bool                                                `json:"gameCenterBlocked,omitempty"`
	GroupAssignments                                *[]DeviceConfigurationGroupAssignment                `json:"groupAssignments,omitempty"`
	ICloudBlockActivityContinuation                 *bool                                                `json:"iCloudBlockActivityContinuation,omitempty"`
	ICloudBlockAddressBook                          *bool                                                `json:"iCloudBlockAddressBook,omitempty"`
	ICloudBlockBookmarks                            *bool                                                `json:"iCloudBlockBookmarks,omitempty"`
	ICloudBlockCalendar                             *bool                                                `json:"iCloudBlockCalendar,omitempty"`
	ICloudBlockDocumentSync                         *bool                                                `json:"iCloudBlockDocumentSync,omitempty"`
	ICloudBlockMail                                 *bool                                                `json:"iCloudBlockMail,omitempty"`
	ICloudBlockNotes                                *bool                                                `json:"iCloudBlockNotes,omitempty"`
	ICloudBlockPhotoLibrary                         *bool                                                `json:"iCloudBlockPhotoLibrary,omitempty"`
	ICloudBlockReminders                            *bool                                                `json:"iCloudBlockReminders,omitempty"`
	ICloudDesktopAndDocumentsBlocked                *bool                                                `json:"iCloudDesktopAndDocumentsBlocked,omitempty"`
	ICloudPrivateRelayBlocked                       *bool                                                `json:"iCloudPrivateRelayBlocked,omitempty"`
	ITunesBlockFileSharing                          *bool                                                `json:"iTunesBlockFileSharing,omitempty"`
	ITunesBlockMusicService                         *bool                                                `json:"iTunesBlockMusicService,omitempty"`
	Id                                              *string                                              `json:"id,omitempty"`
	KeyboardBlockDictation                          *bool                                                `json:"keyboardBlockDictation,omitempty"`
	KeychainBlockCloudSync                          *bool                                                `json:"keychainBlockCloudSync,omitempty"`
	LastModifiedDateTime                            *string                                              `json:"lastModifiedDateTime,omitempty"`
	MultiplayerGamingBlocked                        *bool                                                `json:"multiplayerGamingBlocked,omitempty"`
	ODataType                                       *string                                              `json:"@odata.type,omitempty"`
	PasswordBlockAirDropSharing                     *bool                                                `json:"passwordBlockAirDropSharing,omitempty"`
	PasswordBlockAutoFill                           *bool                                                `json:"passwordBlockAutoFill,omitempty"`
	PasswordBlockFingerprintUnlock                  *bool                                                `json:"passwordBlockFingerprintUnlock,omitempty"`
	PasswordBlockModification                       *bool                                                `json:"passwordBlockModification,omitempty"`
	PasswordBlockProximityRequests                  *bool                                                `json:"passwordBlockProximityRequests,omitempty"`
	PasswordBlockSimple                             *bool                                                `json:"passwordBlockSimple,omitempty"`
	PasswordExpirationDays                          *int64                                               `json:"passwordExpirationDays,omitempty"`
	PasswordMaximumAttemptCount                     *int64                                               `json:"passwordMaximumAttemptCount,omitempty"`
	PasswordMinimumCharacterSetCount                *int64                                               `json:"passwordMinimumCharacterSetCount,omitempty"`
	PasswordMinimumLength                           *int64                                               `json:"passwordMinimumLength,omitempty"`
	PasswordMinutesOfInactivityBeforeLock           *int64                                               `json:"passwordMinutesOfInactivityBeforeLock,omitempty"`
	PasswordMinutesOfInactivityBeforeScreenTimeout  *int64                                               `json:"passwordMinutesOfInactivityBeforeScreenTimeout,omitempty"`
	PasswordMinutesUntilFailedLoginReset            *int64                                               `json:"passwordMinutesUntilFailedLoginReset,omitempty"`
	PasswordPreviousPasswordBlockCount              *int64                                               `json:"passwordPreviousPasswordBlockCount,omitempty"`
	PasswordRequired                                *bool                                                `json:"passwordRequired,omitempty"`
	PasswordRequiredType                            *MacOSGeneralDeviceConfigurationPasswordRequiredType `json:"passwordRequiredType,omitempty"`
	PrivacyAccessControls                           *[]MacOSPrivacyAccessControlItem                     `json:"privacyAccessControls,omitempty"`
	RoleScopeTagIds                                 *[]string                                            `json:"roleScopeTagIds,omitempty"`
	SafariBlockAutofill                             *bool                                                `json:"safariBlockAutofill,omitempty"`
	ScreenCaptureBlocked                            *bool                                                `json:"screenCaptureBlocked,omitempty"`
	SoftwareUpdateMajorOSDeferredInstallDelayInDays *int64                                               `json:"softwareUpdateMajorOSDeferredInstallDelayInDays,omitempty"`
	SoftwareUpdateMinorOSDeferredInstallDelayInDays *int64                                               `json:"softwareUpdateMinorOSDeferredInstallDelayInDays,omitempty"`
	SoftwareUpdateNonOSDeferredInstallDelayInDays   *int64                                               `json:"softwareUpdateNonOSDeferredInstallDelayInDays,omitempty"`
	SoftwareUpdatesEnforcedDelayInDays              *int64                                               `json:"softwareUpdatesEnforcedDelayInDays,omitempty"`
	SpotlightBlockInternetResults                   *bool                                                `json:"spotlightBlockInternetResults,omitempty"`
	SupportsScopeTags                               *bool                                                `json:"supportsScopeTags,omitempty"`
	TouchIdTimeoutInHours                           *int64                                               `json:"touchIdTimeoutInHours,omitempty"`
	UpdateDelayPolicy                               *MacOSGeneralDeviceConfigurationUpdateDelayPolicy    `json:"updateDelayPolicy,omitempty"`
	UserStatusOverview                              *DeviceConfigurationUserOverview                     `json:"userStatusOverview,omitempty"`
	UserStatuses                                    *[]DeviceConfigurationUserStatus                     `json:"userStatuses,omitempty"`
	Version                                         *int64                                               `json:"version,omitempty"`
	WallpaperModificationBlocked                    *bool                                                `json:"wallpaperModificationBlocked,omitempty"`
}
