package beta

// Copyright (c) HashiCorp Inc. All rights reserved.
// Licensed under the MIT License. See NOTICE.txt in the project root for license information.

type DefaultManagedAppProtection struct {
	AllowedAndroidDeviceManufacturers                  *string                                                                        `json:"allowedAndroidDeviceManufacturers,omitempty"`
	AllowedAndroidDeviceModels                         *[]string                                                                      `json:"allowedAndroidDeviceModels,omitempty"`
	AllowedDataIngestionLocations                      *DefaultManagedAppProtectionAllowedDataIngestionLocations                      `json:"allowedDataIngestionLocations,omitempty"`
	AllowedDataStorageLocations                        *DefaultManagedAppProtectionAllowedDataStorageLocations                        `json:"allowedDataStorageLocations,omitempty"`
	AllowedInboundDataTransferSources                  *DefaultManagedAppProtectionAllowedInboundDataTransferSources                  `json:"allowedInboundDataTransferSources,omitempty"`
	AllowedIosDeviceModels                             *string                                                                        `json:"allowedIosDeviceModels,omitempty"`
	AllowedOutboundClipboardSharingExceptionLength     *int64                                                                         `json:"allowedOutboundClipboardSharingExceptionLength,omitempty"`
	AllowedOutboundClipboardSharingLevel               *DefaultManagedAppProtectionAllowedOutboundClipboardSharingLevel               `json:"allowedOutboundClipboardSharingLevel,omitempty"`
	AllowedOutboundDataTransferDestinations            *DefaultManagedAppProtectionAllowedOutboundDataTransferDestinations            `json:"allowedOutboundDataTransferDestinations,omitempty"`
	AppActionIfAccountIsClockedOut                     *DefaultManagedAppProtectionAppActionIfAccountIsClockedOut                     `json:"appActionIfAccountIsClockedOut,omitempty"`
	AppActionIfAndroidDeviceManufacturerNotAllowed     *DefaultManagedAppProtectionAppActionIfAndroidDeviceManufacturerNotAllowed     `json:"appActionIfAndroidDeviceManufacturerNotAllowed,omitempty"`
	AppActionIfAndroidDeviceModelNotAllowed            *DefaultManagedAppProtectionAppActionIfAndroidDeviceModelNotAllowed            `json:"appActionIfAndroidDeviceModelNotAllowed,omitempty"`
	AppActionIfAndroidSafetyNetAppsVerificationFailed  *DefaultManagedAppProtectionAppActionIfAndroidSafetyNetAppsVerificationFailed  `json:"appActionIfAndroidSafetyNetAppsVerificationFailed,omitempty"`
	AppActionIfAndroidSafetyNetDeviceAttestationFailed *DefaultManagedAppProtectionAppActionIfAndroidSafetyNetDeviceAttestationFailed `json:"appActionIfAndroidSafetyNetDeviceAttestationFailed,omitempty"`
	AppActionIfDeviceComplianceRequired                *DefaultManagedAppProtectionAppActionIfDeviceComplianceRequired                `json:"appActionIfDeviceComplianceRequired,omitempty"`
	AppActionIfDeviceLockNotSet                        *DefaultManagedAppProtectionAppActionIfDeviceLockNotSet                        `json:"appActionIfDeviceLockNotSet,omitempty"`
	AppActionIfDevicePasscodeComplexityLessThanHigh    *DefaultManagedAppProtectionAppActionIfDevicePasscodeComplexityLessThanHigh    `json:"appActionIfDevicePasscodeComplexityLessThanHigh,omitempty"`
	AppActionIfDevicePasscodeComplexityLessThanLow     *DefaultManagedAppProtectionAppActionIfDevicePasscodeComplexityLessThanLow     `json:"appActionIfDevicePasscodeComplexityLessThanLow,omitempty"`
	AppActionIfDevicePasscodeComplexityLessThanMedium  *DefaultManagedAppProtectionAppActionIfDevicePasscodeComplexityLessThanMedium  `json:"appActionIfDevicePasscodeComplexityLessThanMedium,omitempty"`
	AppActionIfIosDeviceModelNotAllowed                *DefaultManagedAppProtectionAppActionIfIosDeviceModelNotAllowed                `json:"appActionIfIosDeviceModelNotAllowed,omitempty"`
	AppActionIfMaximumPinRetriesExceeded               *DefaultManagedAppProtectionAppActionIfMaximumPinRetriesExceeded               `json:"appActionIfMaximumPinRetriesExceeded,omitempty"`
	AppActionIfUnableToAuthenticateUser                *DefaultManagedAppProtectionAppActionIfUnableToAuthenticateUser                `json:"appActionIfUnableToAuthenticateUser,omitempty"`
	AppDataEncryptionType                              *DefaultManagedAppProtectionAppDataEncryptionType                              `json:"appDataEncryptionType,omitempty"`
	Apps                                               *[]ManagedMobileApp                                                            `json:"apps,omitempty"`
	BiometricAuthenticationBlocked                     *bool                                                                          `json:"biometricAuthenticationBlocked,omitempty"`
	BlockAfterCompanyPortalUpdateDeferralInDays        *int64                                                                         `json:"blockAfterCompanyPortalUpdateDeferralInDays,omitempty"`
	BlockDataIngestionIntoOrganizationDocuments        *bool                                                                          `json:"blockDataIngestionIntoOrganizationDocuments,omitempty"`
	ConnectToVpnOnLaunch                               *bool                                                                          `json:"connectToVpnOnLaunch,omitempty"`
	ContactSyncBlocked                                 *bool                                                                          `json:"contactSyncBlocked,omitempty"`
	CreatedDateTime                                    *string                                                                        `json:"createdDateTime,omitempty"`
	CustomBrowserDisplayName                           *string                                                                        `json:"customBrowserDisplayName,omitempty"`
	CustomBrowserPackageId                             *string                                                                        `json:"customBrowserPackageId,omitempty"`
	CustomBrowserProtocol                              *string                                                                        `json:"customBrowserProtocol,omitempty"`
	CustomDialerAppDisplayName                         *string                                                                        `json:"customDialerAppDisplayName,omitempty"`
	CustomDialerAppPackageId                           *string                                                                        `json:"customDialerAppPackageId,omitempty"`
	CustomDialerAppProtocol                            *string                                                                        `json:"customDialerAppProtocol,omitempty"`
	CustomSettings                                     *[]KeyValuePair                                                                `json:"customSettings,omitempty"`
	DataBackupBlocked                                  *bool                                                                          `json:"dataBackupBlocked,omitempty"`
	DeployedAppCount                                   *int64                                                                         `json:"deployedAppCount,omitempty"`
	DeploymentSummary                                  *ManagedAppPolicyDeploymentSummary                                             `json:"deploymentSummary,omitempty"`
	Description                                        *string                                                                        `json:"description,omitempty"`
	DeviceComplianceRequired                           *bool                                                                          `json:"deviceComplianceRequired,omitempty"`
	DeviceLockRequired                                 *bool                                                                          `json:"deviceLockRequired,omitempty"`
	DialerRestrictionLevel                             *DefaultManagedAppProtectionDialerRestrictionLevel                             `json:"dialerRestrictionLevel,omitempty"`
	DisableAppEncryptionIfDeviceEncryptionIsEnabled    *bool                                                                          `json:"disableAppEncryptionIfDeviceEncryptionIsEnabled,omitempty"`
	DisableAppPinIfDevicePinIsSet                      *bool                                                                          `json:"disableAppPinIfDevicePinIsSet,omitempty"`
	DisableProtectionOfManagedOutboundOpenInData       *bool                                                                          `json:"disableProtectionOfManagedOutboundOpenInData,omitempty"`
	DisplayName                                        *string                                                                        `json:"displayName,omitempty"`
	EncryptAppData                                     *bool                                                                          `json:"encryptAppData,omitempty"`
	ExemptedAppPackages                                *[]KeyValuePair                                                                `json:"exemptedAppPackages,omitempty"`
	ExemptedAppProtocols                               *[]KeyValuePair                                                                `json:"exemptedAppProtocols,omitempty"`
	FaceIdBlocked                                      *bool                                                                          `json:"faceIdBlocked,omitempty"`
	FilterOpenInToOnlyManagedApps                      *bool                                                                          `json:"filterOpenInToOnlyManagedApps,omitempty"`
	FingerprintAndBiometricEnabled                     *bool                                                                          `json:"fingerprintAndBiometricEnabled,omitempty"`
	FingerprintBlocked                                 *bool                                                                          `json:"fingerprintBlocked,omitempty"`
	GracePeriodToBlockAppsDuringOffClockHours          *string                                                                        `json:"gracePeriodToBlockAppsDuringOffClockHours,omitempty"`
	Id                                                 *string                                                                        `json:"id,omitempty"`
	LastModifiedDateTime                               *string                                                                        `json:"lastModifiedDateTime,omitempty"`
	ManagedBrowser                                     *DefaultManagedAppProtectionManagedBrowser                                     `json:"managedBrowser,omitempty"`
	ManagedBrowserToOpenLinksRequired                  *bool                                                                          `json:"managedBrowserToOpenLinksRequired,omitempty"`
	MaximumAllowedDeviceThreatLevel                    *DefaultManagedAppProtectionMaximumAllowedDeviceThreatLevel                    `json:"maximumAllowedDeviceThreatLevel,omitempty"`
	MaximumPinRetries                                  *int64                                                                         `json:"maximumPinRetries,omitempty"`
	MaximumRequiredOsVersion                           *string                                                                        `json:"maximumRequiredOsVersion,omitempty"`
	MaximumWarningOsVersion                            *string                                                                        `json:"maximumWarningOsVersion,omitempty"`
	MaximumWipeOsVersion                               *string                                                                        `json:"maximumWipeOsVersion,omitempty"`
	MessagingRedirectAppDisplayName                    *string                                                                        `json:"messagingRedirectAppDisplayName,omitempty"`
	MessagingRedirectAppPackageId                      *string                                                                        `json:"messagingRedirectAppPackageId,omitempty"`
	MessagingRedirectAppUrlScheme                      *string                                                                        `json:"messagingRedirectAppUrlScheme,omitempty"`
	MinimumPinLength                                   *int64                                                                         `json:"minimumPinLength,omitempty"`
	MinimumRequiredAppVersion                          *string                                                                        `json:"minimumRequiredAppVersion,omitempty"`
	MinimumRequiredCompanyPortalVersion                *string                                                                        `json:"minimumRequiredCompanyPortalVersion,omitempty"`
	MinimumRequiredOsVersion                           *string                                                                        `json:"minimumRequiredOsVersion,omitempty"`
	MinimumRequiredPatchVersion                        *string                                                                        `json:"minimumRequiredPatchVersion,omitempty"`
	MinimumRequiredSdkVersion                          *string                                                                        `json:"minimumRequiredSdkVersion,omitempty"`
	MinimumWarningAppVersion                           *string                                                                        `json:"minimumWarningAppVersion,omitempty"`
	MinimumWarningCompanyPortalVersion                 *string                                                                        `json:"minimumWarningCompanyPortalVersion,omitempty"`
	MinimumWarningOsVersion                            *string                                                                        `json:"minimumWarningOsVersion,omitempty"`
	MinimumWarningPatchVersion                         *string                                                                        `json:"minimumWarningPatchVersion,omitempty"`
	MinimumWarningSdkVersion                           *string                                                                        `json:"minimumWarningSdkVersion,omitempty"`
	MinimumWipeAppVersion                              *string                                                                        `json:"minimumWipeAppVersion,omitempty"`
	MinimumWipeCompanyPortalVersion                    *string                                                                        `json:"minimumWipeCompanyPortalVersion,omitempty"`
	MinimumWipeOsVersion                               *string                                                                        `json:"minimumWipeOsVersion,omitempty"`
	MinimumWipePatchVersion                            *string                                                                        `json:"minimumWipePatchVersion,omitempty"`
	MinimumWipeSdkVersion                              *string                                                                        `json:"minimumWipeSdkVersion,omitempty"`
	MobileThreatDefensePartnerPriority                 *DefaultManagedAppProtectionMobileThreatDefensePartnerPriority                 `json:"mobileThreatDefensePartnerPriority,omitempty"`
	MobileThreatDefenseRemediationAction               *DefaultManagedAppProtectionMobileThreatDefenseRemediationAction               `json:"mobileThreatDefenseRemediationAction,omitempty"`
	NotificationRestriction                            *DefaultManagedAppProtectionNotificationRestriction                            `json:"notificationRestriction,omitempty"`
	ODataType                                          *string                                                                        `json:"@odata.type,omitempty"`
	OrganizationalCredentialsRequired                  *bool                                                                          `json:"organizationalCredentialsRequired,omitempty"`
	PeriodBeforePinReset                               *string                                                                        `json:"periodBeforePinReset,omitempty"`
	PeriodOfflineBeforeAccessCheck                     *string                                                                        `json:"periodOfflineBeforeAccessCheck,omitempty"`
	PeriodOfflineBeforeWipeIsEnforced                  *string                                                                        `json:"periodOfflineBeforeWipeIsEnforced,omitempty"`
	PeriodOnlineBeforeAccessCheck                      *string                                                                        `json:"periodOnlineBeforeAccessCheck,omitempty"`
	PinCharacterSet                                    *DefaultManagedAppProtectionPinCharacterSet                                    `json:"pinCharacterSet,omitempty"`
	PinRequired                                        *bool                                                                          `json:"pinRequired,omitempty"`
	PinRequiredInsteadOfBiometricTimeout               *string                                                                        `json:"pinRequiredInsteadOfBiometricTimeout,omitempty"`
	PreviousPinBlockCount                              *int64                                                                         `json:"previousPinBlockCount,omitempty"`
	PrintBlocked                                       *bool                                                                          `json:"printBlocked,omitempty"`
	ProtectInboundDataFromUnknownSources               *bool                                                                          `json:"protectInboundDataFromUnknownSources,omitempty"`
	ProtectedMessagingRedirectAppType                  *DefaultManagedAppProtectionProtectedMessagingRedirectAppType                  `json:"protectedMessagingRedirectAppType,omitempty"`
	RequireClass3Biometrics                            *bool                                                                          `json:"requireClass3Biometrics,omitempty"`
	RequirePinAfterBiometricChange                     *bool                                                                          `json:"requirePinAfterBiometricChange,omitempty"`
	RequiredAndroidSafetyNetAppsVerificationType       *DefaultManagedAppProtectionRequiredAndroidSafetyNetAppsVerificationType       `json:"requiredAndroidSafetyNetAppsVerificationType,omitempty"`
	RequiredAndroidSafetyNetDeviceAttestationType      *DefaultManagedAppProtectionRequiredAndroidSafetyNetDeviceAttestationType      `json:"requiredAndroidSafetyNetDeviceAttestationType,omitempty"`
	RequiredAndroidSafetyNetEvaluationType             *DefaultManagedAppProtectionRequiredAndroidSafetyNetEvaluationType             `json:"requiredAndroidSafetyNetEvaluationType,omitempty"`
	RoleScopeTagIds                                    *[]string                                                                      `json:"roleScopeTagIds,omitempty"`
	SaveAsBlocked                                      *bool                                                                          `json:"saveAsBlocked,omitempty"`
	ScreenCaptureBlocked                               *bool                                                                          `json:"screenCaptureBlocked,omitempty"`
	SimplePinBlocked                                   *bool                                                                          `json:"simplePinBlocked,omitempty"`
	ThirdPartyKeyboardsBlocked                         *bool                                                                          `json:"thirdPartyKeyboardsBlocked,omitempty"`
	Version                                            *string                                                                        `json:"version,omitempty"`
	WarnAfterCompanyPortalUpdateDeferralInDays         *int64                                                                         `json:"warnAfterCompanyPortalUpdateDeferralInDays,omitempty"`
	WipeAfterCompanyPortalUpdateDeferralInDays         *int64                                                                         `json:"wipeAfterCompanyPortalUpdateDeferralInDays,omitempty"`
}
