package communicationsgateways

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See NOTICE.txt in the project root for license information.

type CommunicationsGatewayProperties struct {
	AllocatedMediaAddressPrefixes     *[]string                          `json:"allocatedMediaAddressPrefixes,omitempty"`
	AllocatedSignalingAddressPrefixes *[]string                          `json:"allocatedSignalingAddressPrefixes,omitempty"`
	ApiBridge                         *ApiBridgeProperties               `json:"apiBridge,omitempty"`
	AutoGeneratedDomainNameLabel      *string                            `json:"autoGeneratedDomainNameLabel,omitempty"`
	AutoGeneratedDomainNameLabelScope *AutoGeneratedDomainNameLabelScope `json:"autoGeneratedDomainNameLabelScope,omitempty"`
	Codecs                            []TeamsCodecs                      `json:"codecs"`
	Connectivity                      Connectivity                       `json:"connectivity"`
	CustomSipHeaders                  *CustomSipHeadersProperties        `json:"customSipHeaders,omitempty"`
	DnsDelegations                    *DnsDelegationsProperties          `json:"dnsDelegations,omitempty"`
	E911Type                          E911Type                           `json:"e911Type"`
	EmergencyDialStrings              *[]string                          `json:"emergencyDialStrings,omitempty"`
	IntegratedMcpEnabled              *bool                              `json:"integratedMcpEnabled,omitempty"`
	OnPremMcpEnabled                  *bool                              `json:"onPremMcpEnabled,omitempty"`
	Platforms                         []CommunicationsPlatform           `json:"platforms"`
	ProvisioningState                 *ProvisioningState                 `json:"provisioningState,omitempty"`
	ServiceLocations                  []ServiceRegionProperties          `json:"serviceLocations"`
	Status                            *Status                            `json:"status,omitempty"`
	TeamsVoicemailPilotNumber         *string                            `json:"teamsVoicemailPilotNumber,omitempty"`
}
