package models

// Copyright (c) HashiCorp Inc. All rights reserved.
// Licensed under the MIT License. See NOTICE.txt in the project root for license information.

type IosGeneralDeviceConfiguration struct {
	AccountBlockModification                       *bool                                                `json:"accountBlockModification,omitempty"`
	ActivationLockAllowWhenSupervised              *bool                                                `json:"activationLockAllowWhenSupervised,omitempty"`
	AirDropBlocked                                 *bool                                                `json:"airDropBlocked,omitempty"`
	AirDropForceUnmanagedDropTarget                *bool                                                `json:"airDropForceUnmanagedDropTarget,omitempty"`
	AirPlayForcePairingPasswordForOutgoingRequests *bool                                                `json:"airPlayForcePairingPasswordForOutgoingRequests,omitempty"`
	AppStoreBlockAutomaticDownloads                *bool                                                `json:"appStoreBlockAutomaticDownloads,omitempty"`
	AppStoreBlockInAppPurchases                    *bool                                                `json:"appStoreBlockInAppPurchases,omitempty"`
	AppStoreBlockUIAppInstallation                 *bool                                                `json:"appStoreBlockUIAppInstallation,omitempty"`
	AppStoreBlocked                                *bool                                                `json:"appStoreBlocked,omitempty"`
	AppStoreRequirePassword                        *bool                                                `json:"appStoreRequirePassword,omitempty"`
	AppleNewsBlocked                               *bool                                                `json:"appleNewsBlocked,omitempty"`
	AppleWatchBlockPairing                         *bool                                                `json:"appleWatchBlockPairing,omitempty"`
	AppleWatchForceWristDetection                  *bool                                                `json:"appleWatchForceWristDetection,omitempty"`
	AppsSingleAppModeList                          *[]AppListItem                                       `json:"appsSingleAppModeList,omitempty"`
	AppsVisibilityList                             *[]AppListItem                                       `json:"appsVisibilityList,omitempty"`
	AppsVisibilityListType                         *IosGeneralDeviceConfigurationAppsVisibilityListType `json:"appsVisibilityListType,omitempty"`
	Assignments                                    *[]DeviceConfigurationAssignment                     `json:"assignments,omitempty"`
	BluetoothBlockModification                     *bool                                                `json:"bluetoothBlockModification,omitempty"`
	CameraBlocked                                  *bool                                                `json:"cameraBlocked,omitempty"`
	CellularBlockDataRoaming                       *bool                                                `json:"cellularBlockDataRoaming,omitempty"`
	CellularBlockGlobalBackgroundFetchWhileRoaming *bool                                                `json:"cellularBlockGlobalBackgroundFetchWhileRoaming,omitempty"`
	CellularBlockPerAppDataModification            *bool                                                `json:"cellularBlockPerAppDataModification,omitempty"`
	CellularBlockPersonalHotspot                   *bool                                                `json:"cellularBlockPersonalHotspot,omitempty"`
	CellularBlockVoiceRoaming                      *bool                                                `json:"cellularBlockVoiceRoaming,omitempty"`
	CertificatesBlockUntrustedTlsCertificates      *bool                                                `json:"certificatesBlockUntrustedTlsCertificates,omitempty"`
	ClassroomAppBlockRemoteScreenObservation       *bool                                                `json:"classroomAppBlockRemoteScreenObservation,omitempty"`
	ClassroomAppForceUnpromptedScreenObservation   *bool                                                `json:"classroomAppForceUnpromptedScreenObservation,omitempty"`
	CompliantAppListType                           *IosGeneralDeviceConfigurationCompliantAppListType   `json:"compliantAppListType,omitempty"`
	CompliantAppsList                              *[]AppListItem                                       `json:"compliantAppsList,omitempty"`
	ConfigurationProfileBlockChanges               *bool                                                `json:"configurationProfileBlockChanges,omitempty"`
	CreatedDateTime                                *string                                              `json:"createdDateTime,omitempty"`
	DefinitionLookupBlocked                        *bool                                                `json:"definitionLookupBlocked,omitempty"`
	Description                                    *string                                              `json:"description,omitempty"`
	DeviceBlockEnableRestrictions                  *bool                                                `json:"deviceBlockEnableRestrictions,omitempty"`
	DeviceBlockEraseContentAndSettings             *bool                                                `json:"deviceBlockEraseContentAndSettings,omitempty"`
	DeviceBlockNameModification                    *bool                                                `json:"deviceBlockNameModification,omitempty"`
	DeviceSettingStateSummaries                    *[]SettingStateDeviceSummary                         `json:"deviceSettingStateSummaries,omitempty"`
	DeviceStatusOverview                           *DeviceConfigurationDeviceOverview                   `json:"deviceStatusOverview,omitempty"`
	DeviceStatuses                                 *[]DeviceConfigurationDeviceStatus                   `json:"deviceStatuses,omitempty"`
	DiagnosticDataBlockSubmission                  *bool                                                `json:"diagnosticDataBlockSubmission,omitempty"`
	DiagnosticDataBlockSubmissionModification      *bool                                                `json:"diagnosticDataBlockSubmissionModification,omitempty"`
	DisplayName                                    *string                                              `json:"displayName,omitempty"`
	DocumentsBlockManagedDocumentsInUnmanagedApps  *bool                                                `json:"documentsBlockManagedDocumentsInUnmanagedApps,omitempty"`
	DocumentsBlockUnmanagedDocumentsInManagedApps  *bool                                                `json:"documentsBlockUnmanagedDocumentsInManagedApps,omitempty"`
	EmailInDomainSuffixes                          *[]string                                            `json:"emailInDomainSuffixes,omitempty"`
	EnterpriseAppBlockTrust                        *bool                                                `json:"enterpriseAppBlockTrust,omitempty"`
	EnterpriseAppBlockTrustModification            *bool                                                `json:"enterpriseAppBlockTrustModification,omitempty"`
	FaceTimeBlocked                                *bool                                                `json:"faceTimeBlocked,omitempty"`
	FindMyFriendsBlocked                           *bool                                                `json:"findMyFriendsBlocked,omitempty"`
	GameCenterBlocked                              *bool                                                `json:"gameCenterBlocked,omitempty"`
	GamingBlockGameCenterFriends                   *bool                                                `json:"gamingBlockGameCenterFriends,omitempty"`
	GamingBlockMultiplayer                         *bool                                                `json:"gamingBlockMultiplayer,omitempty"`
	HostPairingBlocked                             *bool                                                `json:"hostPairingBlocked,omitempty"`
	IBooksStoreBlockErotica                        *bool                                                `json:"iBooksStoreBlockErotica,omitempty"`
	IBooksStoreBlocked                             *bool                                                `json:"iBooksStoreBlocked,omitempty"`
	ICloudBlockActivityContinuation                *bool                                                `json:"iCloudBlockActivityContinuation,omitempty"`
	ICloudBlockBackup                              *bool                                                `json:"iCloudBlockBackup,omitempty"`
	ICloudBlockDocumentSync                        *bool                                                `json:"iCloudBlockDocumentSync,omitempty"`
	ICloudBlockManagedAppsSync                     *bool                                                `json:"iCloudBlockManagedAppsSync,omitempty"`
	ICloudBlockPhotoLibrary                        *bool                                                `json:"iCloudBlockPhotoLibrary,omitempty"`
	ICloudBlockPhotoStreamSync                     *bool                                                `json:"iCloudBlockPhotoStreamSync,omitempty"`
	ICloudBlockSharedPhotoStream                   *bool                                                `json:"iCloudBlockSharedPhotoStream,omitempty"`
	ICloudRequireEncryptedBackup                   *bool                                                `json:"iCloudRequireEncryptedBackup,omitempty"`
	ITunesBlockExplicitContent                     *bool                                                `json:"iTunesBlockExplicitContent,omitempty"`
	ITunesBlockMusicService                        *bool                                                `json:"iTunesBlockMusicService,omitempty"`
	ITunesBlockRadio                               *bool                                                `json:"iTunesBlockRadio,omitempty"`
	Id                                             *string                                              `json:"id,omitempty"`
	KeyboardBlockAutoCorrect                       *bool                                                `json:"keyboardBlockAutoCorrect,omitempty"`
	KeyboardBlockDictation                         *bool                                                `json:"keyboardBlockDictation,omitempty"`
	KeyboardBlockPredictive                        *bool                                                `json:"keyboardBlockPredictive,omitempty"`
	KeyboardBlockShortcuts                         *bool                                                `json:"keyboardBlockShortcuts,omitempty"`
	KeyboardBlockSpellCheck                        *bool                                                `json:"keyboardBlockSpellCheck,omitempty"`
	KioskModeAllowAssistiveSpeak                   *bool                                                `json:"kioskModeAllowAssistiveSpeak,omitempty"`
	KioskModeAllowAssistiveTouchSettings           *bool                                                `json:"kioskModeAllowAssistiveTouchSettings,omitempty"`
	KioskModeAllowAutoLock                         *bool                                                `json:"kioskModeAllowAutoLock,omitempty"`
	KioskModeAllowColorInversionSettings           *bool                                                `json:"kioskModeAllowColorInversionSettings,omitempty"`
	KioskModeAllowRingerSwitch                     *bool                                                `json:"kioskModeAllowRingerSwitch,omitempty"`
	KioskModeAllowScreenRotation                   *bool                                                `json:"kioskModeAllowScreenRotation,omitempty"`
	KioskModeAllowSleepButton                      *bool                                                `json:"kioskModeAllowSleepButton,omitempty"`
	KioskModeAllowTouchscreen                      *bool                                                `json:"kioskModeAllowTouchscreen,omitempty"`
	KioskModeAllowVoiceOverSettings                *bool                                                `json:"kioskModeAllowVoiceOverSettings,omitempty"`
	KioskModeAllowVolumeButtons                    *bool                                                `json:"kioskModeAllowVolumeButtons,omitempty"`
	KioskModeAllowZoomSettings                     *bool                                                `json:"kioskModeAllowZoomSettings,omitempty"`
	KioskModeAppStoreUrl                           *string                                              `json:"kioskModeAppStoreUrl,omitempty"`
	KioskModeBuiltInAppId                          *string                                              `json:"kioskModeBuiltInAppId,omitempty"`
	KioskModeManagedAppId                          *string                                              `json:"kioskModeManagedAppId,omitempty"`
	KioskModeRequireAssistiveTouch                 *bool                                                `json:"kioskModeRequireAssistiveTouch,omitempty"`
	KioskModeRequireColorInversion                 *bool                                                `json:"kioskModeRequireColorInversion,omitempty"`
	KioskModeRequireMonoAudio                      *bool                                                `json:"kioskModeRequireMonoAudio,omitempty"`
	KioskModeRequireVoiceOver                      *bool                                                `json:"kioskModeRequireVoiceOver,omitempty"`
	KioskModeRequireZoom                           *bool                                                `json:"kioskModeRequireZoom,omitempty"`
	LastModifiedDateTime                           *string                                              `json:"lastModifiedDateTime,omitempty"`
	LockScreenBlockControlCenter                   *bool                                                `json:"lockScreenBlockControlCenter,omitempty"`
	LockScreenBlockNotificationView                *bool                                                `json:"lockScreenBlockNotificationView,omitempty"`
	LockScreenBlockPassbook                        *bool                                                `json:"lockScreenBlockPassbook,omitempty"`
	LockScreenBlockTodayView                       *bool                                                `json:"lockScreenBlockTodayView,omitempty"`
	MediaContentRatingApps                         *IosGeneralDeviceConfigurationMediaContentRatingApps `json:"mediaContentRatingApps,omitempty"`
	MediaContentRatingAustralia                    *MediaContentRatingAustralia                         `json:"mediaContentRatingAustralia,omitempty"`
	MediaContentRatingCanada                       *MediaContentRatingCanada                            `json:"mediaContentRatingCanada,omitempty"`
	MediaContentRatingFrance                       *MediaContentRatingFrance                            `json:"mediaContentRatingFrance,omitempty"`
	MediaContentRatingGermany                      *MediaContentRatingGermany                           `json:"mediaContentRatingGermany,omitempty"`
	MediaContentRatingIreland                      *MediaContentRatingIreland                           `json:"mediaContentRatingIreland,omitempty"`
	MediaContentRatingJapan                        *MediaContentRatingJapan                             `json:"mediaContentRatingJapan,omitempty"`
	MediaContentRatingNewZealand                   *MediaContentRatingNewZealand                        `json:"mediaContentRatingNewZealand,omitempty"`
	MediaContentRatingUnitedKingdom                *MediaContentRatingUnitedKingdom                     `json:"mediaContentRatingUnitedKingdom,omitempty"`
	MediaContentRatingUnitedStates                 *MediaContentRatingUnitedStates                      `json:"mediaContentRatingUnitedStates,omitempty"`
	MessagesBlocked                                *bool                                                `json:"messagesBlocked,omitempty"`
	NetworkUsageRules                              *[]IosNetworkUsageRule                               `json:"networkUsageRules,omitempty"`
	NotificationsBlockSettingsModification         *bool                                                `json:"notificationsBlockSettingsModification,omitempty"`
	ODataType                                      *string                                              `json:"@odata.type,omitempty"`
	PasscodeBlockFingerprintModification           *bool                                                `json:"passcodeBlockFingerprintModification,omitempty"`
	PasscodeBlockFingerprintUnlock                 *bool                                                `json:"passcodeBlockFingerprintUnlock,omitempty"`
	PasscodeBlockModification                      *bool                                                `json:"passcodeBlockModification,omitempty"`
	PasscodeBlockSimple                            *bool                                                `json:"passcodeBlockSimple,omitempty"`
	PasscodeExpirationDays                         *int64                                               `json:"passcodeExpirationDays,omitempty"`
	PasscodeMinimumCharacterSetCount               *int64                                               `json:"passcodeMinimumCharacterSetCount,omitempty"`
	PasscodeMinimumLength                          *int64                                               `json:"passcodeMinimumLength,omitempty"`
	PasscodeMinutesOfInactivityBeforeLock          *int64                                               `json:"passcodeMinutesOfInactivityBeforeLock,omitempty"`
	PasscodeMinutesOfInactivityBeforeScreenTimeout *int64                                               `json:"passcodeMinutesOfInactivityBeforeScreenTimeout,omitempty"`
	PasscodePreviousPasscodeBlockCount             *int64                                               `json:"passcodePreviousPasscodeBlockCount,omitempty"`
	PasscodeRequired                               *bool                                                `json:"passcodeRequired,omitempty"`
	PasscodeRequiredType                           *IosGeneralDeviceConfigurationPasscodeRequiredType   `json:"passcodeRequiredType,omitempty"`
	PasscodeSignInFailureCountBeforeWipe           *int64                                               `json:"passcodeSignInFailureCountBeforeWipe,omitempty"`
	PodcastsBlocked                                *bool                                                `json:"podcastsBlocked,omitempty"`
	SafariBlockAutofill                            *bool                                                `json:"safariBlockAutofill,omitempty"`
	SafariBlockJavaScript                          *bool                                                `json:"safariBlockJavaScript,omitempty"`
	SafariBlockPopups                              *bool                                                `json:"safariBlockPopups,omitempty"`
	SafariBlocked                                  *bool                                                `json:"safariBlocked,omitempty"`
	SafariCookieSettings                           *IosGeneralDeviceConfigurationSafariCookieSettings   `json:"safariCookieSettings,omitempty"`
	SafariManagedDomains                           *[]string                                            `json:"safariManagedDomains,omitempty"`
	SafariPasswordAutoFillDomains                  *[]string                                            `json:"safariPasswordAutoFillDomains,omitempty"`
	SafariRequireFraudWarning                      *bool                                                `json:"safariRequireFraudWarning,omitempty"`
	ScreenCaptureBlocked                           *bool                                                `json:"screenCaptureBlocked,omitempty"`
	SiriBlockUserGeneratedContent                  *bool                                                `json:"siriBlockUserGeneratedContent,omitempty"`
	SiriBlocked                                    *bool                                                `json:"siriBlocked,omitempty"`
	SiriBlockedWhenLocked                          *bool                                                `json:"siriBlockedWhenLocked,omitempty"`
	SiriRequireProfanityFilter                     *bool                                                `json:"siriRequireProfanityFilter,omitempty"`
	SpotlightBlockInternetResults                  *bool                                                `json:"spotlightBlockInternetResults,omitempty"`
	UserStatusOverview                             *DeviceConfigurationUserOverview                     `json:"userStatusOverview,omitempty"`
	UserStatuses                                   *[]DeviceConfigurationUserStatus                     `json:"userStatuses,omitempty"`
	Version                                        *int64                                               `json:"version,omitempty"`
	VoiceDialingBlocked                            *bool                                                `json:"voiceDialingBlocked,omitempty"`
	WallpaperBlockModification                     *bool                                                `json:"wallpaperBlockModification,omitempty"`
	WiFiConnectOnlyToConfiguredNetworks            *bool                                                `json:"wiFiConnectOnlyToConfiguredNetworks,omitempty"`
}
