package virtualendpointprovisioningpolicy

// Copyright (c) HashiCorp Inc. All rights reserved.
// Licensed under the MIT License. See NOTICE.txt in the project root for license information.

type ManagedDevice struct {
	AadRegistered                               *bool                                       `json:"aadRegistered,omitempty"`
	ActivationLockBypassCode                    *string                                     `json:"activationLockBypassCode,omitempty"`
	AndroidSecurityPatchLevel                   *string                                     `json:"androidSecurityPatchLevel,omitempty"`
	AssignmentFilterEvaluationStatusDetails     *[]AssignmentFilterEvaluationStatusDetails  `json:"assignmentFilterEvaluationStatusDetails,omitempty"`
	AutopilotEnrolled                           *bool                                       `json:"autopilotEnrolled,omitempty"`
	AzureADDeviceId                             *string                                     `json:"azureADDeviceId,omitempty"`
	AzureADRegistered                           *bool                                       `json:"azureADRegistered,omitempty"`
	AzureActiveDirectoryDeviceId                *string                                     `json:"azureActiveDirectoryDeviceId,omitempty"`
	BootstrapTokenEscrowed                      *bool                                       `json:"bootstrapTokenEscrowed,omitempty"`
	ChassisType                                 *ManagedDeviceChassisType                   `json:"chassisType,omitempty"`
	ChromeOSDeviceInfo                          *[]ChromeOSDeviceProperty                   `json:"chromeOSDeviceInfo,omitempty"`
	CloudPCRemoteActionResults                  *[]CloudPCRemoteActionResult                `json:"cloudPcRemoteActionResults,omitempty"`
	ComplianceGracePeriodExpirationDateTime     *string                                     `json:"complianceGracePeriodExpirationDateTime,omitempty"`
	ComplianceState                             *ManagedDeviceComplianceState               `json:"complianceState,omitempty"`
	ConfigurationManagerClientEnabledFeatures   *ConfigurationManagerClientEnabledFeatures  `json:"configurationManagerClientEnabledFeatures,omitempty"`
	ConfigurationManagerClientHealthState       *ConfigurationManagerClientHealthState      `json:"configurationManagerClientHealthState,omitempty"`
	ConfigurationManagerClientInformation       *ConfigurationManagerClientInformation      `json:"configurationManagerClientInformation,omitempty"`
	DetectedApps                                *[]DetectedApp                              `json:"detectedApps,omitempty"`
	DeviceActionResults                         *[]DeviceActionResult                       `json:"deviceActionResults,omitempty"`
	DeviceCategory                              *DeviceCategory                             `json:"deviceCategory,omitempty"`
	DeviceCategoryDisplayName                   *string                                     `json:"deviceCategoryDisplayName,omitempty"`
	DeviceCompliancePolicyStates                *[]DeviceCompliancePolicyState              `json:"deviceCompliancePolicyStates,omitempty"`
	DeviceConfigurationStates                   *[]DeviceConfigurationState                 `json:"deviceConfigurationStates,omitempty"`
	DeviceEnrollmentType                        *ManagedDeviceDeviceEnrollmentType          `json:"deviceEnrollmentType,omitempty"`
	DeviceFirmwareConfigurationInterfaceManaged *bool                                       `json:"deviceFirmwareConfigurationInterfaceManaged,omitempty"`
	DeviceHealthAttestationState                *DeviceHealthAttestationState               `json:"deviceHealthAttestationState,omitempty"`
	DeviceHealthScriptStates                    *[]DeviceHealthScriptPolicyState            `json:"deviceHealthScriptStates,omitempty"`
	DeviceIdentityAttestationDetail             *DeviceIdentityAttestationDetail            `json:"deviceIdentityAttestationDetail,omitempty"`
	DeviceName                                  *string                                     `json:"deviceName,omitempty"`
	DeviceRegistrationState                     *ManagedDeviceDeviceRegistrationState       `json:"deviceRegistrationState,omitempty"`
	DeviceType                                  *ManagedDeviceDeviceType                    `json:"deviceType,omitempty"`
	EasActivated                                *bool                                       `json:"easActivated,omitempty"`
	EasActivationDateTime                       *string                                     `json:"easActivationDateTime,omitempty"`
	EasDeviceId                                 *string                                     `json:"easDeviceId,omitempty"`
	EmailAddress                                *string                                     `json:"emailAddress,omitempty"`
	EnrolledDateTime                            *string                                     `json:"enrolledDateTime,omitempty"`
	EnrollmentProfileName                       *string                                     `json:"enrollmentProfileName,omitempty"`
	EthernetMacAddress                          *string                                     `json:"ethernetMacAddress,omitempty"`
	ExchangeAccessState                         *ManagedDeviceExchangeAccessState           `json:"exchangeAccessState,omitempty"`
	ExchangeAccessStateReason                   *ManagedDeviceExchangeAccessStateReason     `json:"exchangeAccessStateReason,omitempty"`
	ExchangeLastSuccessfulSyncDateTime          *string                                     `json:"exchangeLastSuccessfulSyncDateTime,omitempty"`
	FreeStorageSpaceInBytes                     *int64                                      `json:"freeStorageSpaceInBytes,omitempty"`
	HardwareInformation                         *HardwareInformation                        `json:"hardwareInformation,omitempty"`
	Iccid                                       *string                                     `json:"iccid,omitempty"`
	Id                                          *string                                     `json:"id,omitempty"`
	Imei                                        *string                                     `json:"imei,omitempty"`
	IsEncrypted                                 *bool                                       `json:"isEncrypted,omitempty"`
	IsSupervised                                *bool                                       `json:"isSupervised,omitempty"`
	JailBroken                                  *string                                     `json:"jailBroken,omitempty"`
	JoinType                                    *ManagedDeviceJoinType                      `json:"joinType,omitempty"`
	LastSyncDateTime                            *string                                     `json:"lastSyncDateTime,omitempty"`
	LogCollectionRequests                       *[]DeviceLogCollectionResponse              `json:"logCollectionRequests,omitempty"`
	LostModeState                               *ManagedDeviceLostModeState                 `json:"lostModeState,omitempty"`
	ManagedDeviceMobileAppConfigurationStates   *[]ManagedDeviceMobileAppConfigurationState `json:"managedDeviceMobileAppConfigurationStates,omitempty"`
	ManagedDeviceName                           *string                                     `json:"managedDeviceName,omitempty"`
	ManagedDeviceOwnerType                      *ManagedDeviceManagedDeviceOwnerType        `json:"managedDeviceOwnerType,omitempty"`
	ManagementAgent                             *ManagedDeviceManagementAgent               `json:"managementAgent,omitempty"`
	ManagementCertificateExpirationDate         *string                                     `json:"managementCertificateExpirationDate,omitempty"`
	ManagementFeatures                          *ManagedDeviceManagementFeatures            `json:"managementFeatures,omitempty"`
	ManagementState                             *ManagedDeviceManagementState               `json:"managementState,omitempty"`
	Manufacturer                                *string                                     `json:"manufacturer,omitempty"`
	Meid                                        *string                                     `json:"meid,omitempty"`
	Model                                       *string                                     `json:"model,omitempty"`
	Notes                                       *string                                     `json:"notes,omitempty"`
	ODataType                                   *string                                     `json:"@odata.type,omitempty"`
	OperatingSystem                             *string                                     `json:"operatingSystem,omitempty"`
	OsVersion                                   *string                                     `json:"osVersion,omitempty"`
	OwnerType                                   *ManagedDeviceOwnerType                     `json:"ownerType,omitempty"`
	PartnerReportedThreatState                  *ManagedDevicePartnerReportedThreatState    `json:"partnerReportedThreatState,omitempty"`
	PhoneNumber                                 *string                                     `json:"phoneNumber,omitempty"`
	PhysicalMemoryInBytes                       *int64                                      `json:"physicalMemoryInBytes,omitempty"`
	PreferMdmOverGroupPolicyAppliedDateTime     *string                                     `json:"preferMdmOverGroupPolicyAppliedDateTime,omitempty"`
	ProcessorArchitecture                       *ManagedDeviceProcessorArchitecture         `json:"processorArchitecture,omitempty"`
	RemoteAssistanceSessionErrorDetails         *string                                     `json:"remoteAssistanceSessionErrorDetails,omitempty"`
	RemoteAssistanceSessionUrl                  *string                                     `json:"remoteAssistanceSessionUrl,omitempty"`
	RequireUserEnrollmentApproval               *bool                                       `json:"requireUserEnrollmentApproval,omitempty"`
	RetireAfterDateTime                         *string                                     `json:"retireAfterDateTime,omitempty"`
	RoleScopeTagIds                             *[]string                                   `json:"roleScopeTagIds,omitempty"`
	SecurityBaselineStates                      *[]SecurityBaselineState                    `json:"securityBaselineStates,omitempty"`
	SecurityPatchLevel                          *string                                     `json:"securityPatchLevel,omitempty"`
	SerialNumber                                *string                                     `json:"serialNumber,omitempty"`
	SkuFamily                                   *string                                     `json:"skuFamily,omitempty"`
	SkuNumber                                   *int64                                      `json:"skuNumber,omitempty"`
	SpecificationVersion                        *string                                     `json:"specificationVersion,omitempty"`
	SubscriberCarrier                           *string                                     `json:"subscriberCarrier,omitempty"`
	TotalStorageSpaceInBytes                    *int64                                      `json:"totalStorageSpaceInBytes,omitempty"`
	Udid                                        *string                                     `json:"udid,omitempty"`
	UserDisplayName                             *string                                     `json:"userDisplayName,omitempty"`
	UserId                                      *string                                     `json:"userId,omitempty"`
	UserPrincipalName                           *string                                     `json:"userPrincipalName,omitempty"`
	Users                                       *[]User                                     `json:"users,omitempty"`
	UsersLoggedOn                               *[]LoggedOnUser                             `json:"usersLoggedOn,omitempty"`
	WiFiMacAddress                              *string                                     `json:"wiFiMacAddress,omitempty"`
	WindowsActiveMalwareCount                   *int64                                      `json:"windowsActiveMalwareCount,omitempty"`
	WindowsProtectionState                      *WindowsProtectionState                     `json:"windowsProtectionState,omitempty"`
	WindowsRemediatedMalwareCount               *int64                                      `json:"windowsRemediatedMalwareCount,omitempty"`
}
