package resourceproviders

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See NOTICE.txt in the project root for license information.

type DnlResourceNameAvailabilityRequest struct {
	AutoGeneratedDomainNameLabelScope *string                `json:"autoGeneratedDomainNameLabelScope,omitempty"`
	Name                              string                 `json:"name"`
	ResourceGroupName                 *string                `json:"resourceGroupName,omitempty"`
	Type                              CheckNameResourceTypes `json:"type"`
}
