package models

import "strings"

// Copyright (c) HashiCorp Inc. All rights reserved.
// Licensed under the MIT License. See NOTICE.txt in the project root for license information.

type Windows10EndpointProtectionConfigurationDefenderOfficeCommunicationAppsLaunchChildProcess string

const (
	Windows10EndpointProtectionConfigurationDefenderOfficeCommunicationAppsLaunchChildProcessauditMode     Windows10EndpointProtectionConfigurationDefenderOfficeCommunicationAppsLaunchChildProcess = "AuditMode"
	Windows10EndpointProtectionConfigurationDefenderOfficeCommunicationAppsLaunchChildProcessenable        Windows10EndpointProtectionConfigurationDefenderOfficeCommunicationAppsLaunchChildProcess = "Enable"
	Windows10EndpointProtectionConfigurationDefenderOfficeCommunicationAppsLaunchChildProcessnotConfigured Windows10EndpointProtectionConfigurationDefenderOfficeCommunicationAppsLaunchChildProcess = "NotConfigured"
	Windows10EndpointProtectionConfigurationDefenderOfficeCommunicationAppsLaunchChildProcessuserDefined   Windows10EndpointProtectionConfigurationDefenderOfficeCommunicationAppsLaunchChildProcess = "UserDefined"
	Windows10EndpointProtectionConfigurationDefenderOfficeCommunicationAppsLaunchChildProcesswarn          Windows10EndpointProtectionConfigurationDefenderOfficeCommunicationAppsLaunchChildProcess = "Warn"
)

func PossibleValuesForWindows10EndpointProtectionConfigurationDefenderOfficeCommunicationAppsLaunchChildProcess() []string {
	return []string{
		string(Windows10EndpointProtectionConfigurationDefenderOfficeCommunicationAppsLaunchChildProcessauditMode),
		string(Windows10EndpointProtectionConfigurationDefenderOfficeCommunicationAppsLaunchChildProcessenable),
		string(Windows10EndpointProtectionConfigurationDefenderOfficeCommunicationAppsLaunchChildProcessnotConfigured),
		string(Windows10EndpointProtectionConfigurationDefenderOfficeCommunicationAppsLaunchChildProcessuserDefined),
		string(Windows10EndpointProtectionConfigurationDefenderOfficeCommunicationAppsLaunchChildProcesswarn),
	}
}

func parseWindows10EndpointProtectionConfigurationDefenderOfficeCommunicationAppsLaunchChildProcess(input string) (*Windows10EndpointProtectionConfigurationDefenderOfficeCommunicationAppsLaunchChildProcess, error) {
	vals := map[string]Windows10EndpointProtectionConfigurationDefenderOfficeCommunicationAppsLaunchChildProcess{
		"auditmode":     Windows10EndpointProtectionConfigurationDefenderOfficeCommunicationAppsLaunchChildProcessauditMode,
		"enable":        Windows10EndpointProtectionConfigurationDefenderOfficeCommunicationAppsLaunchChildProcessenable,
		"notconfigured": Windows10EndpointProtectionConfigurationDefenderOfficeCommunicationAppsLaunchChildProcessnotConfigured,
		"userdefined":   Windows10EndpointProtectionConfigurationDefenderOfficeCommunicationAppsLaunchChildProcessuserDefined,
		"warn":          Windows10EndpointProtectionConfigurationDefenderOfficeCommunicationAppsLaunchChildProcesswarn,
	}
	if v, ok := vals[strings.ToLower(input)]; ok {
		return &v, nil
	}

	// otherwise presume it's an undefined value and best-effort it
	out := Windows10EndpointProtectionConfigurationDefenderOfficeCommunicationAppsLaunchChildProcess(input)
	return &out, nil
}
