package models

import "strings"

// Copyright (c) HashiCorp Inc. All rights reserved.
// Licensed under the MIT License. See NOTICE.txt in the project root for license information.

type Windows10EndpointProtectionConfigurationDefenderOfficeAppsExecutableContentCreationOrLaunchType string

const (
	Windows10EndpointProtectionConfigurationDefenderOfficeAppsExecutableContentCreationOrLaunchTypeauditMode   Windows10EndpointProtectionConfigurationDefenderOfficeAppsExecutableContentCreationOrLaunchType = "AuditMode"
	Windows10EndpointProtectionConfigurationDefenderOfficeAppsExecutableContentCreationOrLaunchTypeblock       Windows10EndpointProtectionConfigurationDefenderOfficeAppsExecutableContentCreationOrLaunchType = "Block"
	Windows10EndpointProtectionConfigurationDefenderOfficeAppsExecutableContentCreationOrLaunchTypedisable     Windows10EndpointProtectionConfigurationDefenderOfficeAppsExecutableContentCreationOrLaunchType = "Disable"
	Windows10EndpointProtectionConfigurationDefenderOfficeAppsExecutableContentCreationOrLaunchTypeuserDefined Windows10EndpointProtectionConfigurationDefenderOfficeAppsExecutableContentCreationOrLaunchType = "UserDefined"
	Windows10EndpointProtectionConfigurationDefenderOfficeAppsExecutableContentCreationOrLaunchTypewarn        Windows10EndpointProtectionConfigurationDefenderOfficeAppsExecutableContentCreationOrLaunchType = "Warn"
)

func PossibleValuesForWindows10EndpointProtectionConfigurationDefenderOfficeAppsExecutableContentCreationOrLaunchType() []string {
	return []string{
		string(Windows10EndpointProtectionConfigurationDefenderOfficeAppsExecutableContentCreationOrLaunchTypeauditMode),
		string(Windows10EndpointProtectionConfigurationDefenderOfficeAppsExecutableContentCreationOrLaunchTypeblock),
		string(Windows10EndpointProtectionConfigurationDefenderOfficeAppsExecutableContentCreationOrLaunchTypedisable),
		string(Windows10EndpointProtectionConfigurationDefenderOfficeAppsExecutableContentCreationOrLaunchTypeuserDefined),
		string(Windows10EndpointProtectionConfigurationDefenderOfficeAppsExecutableContentCreationOrLaunchTypewarn),
	}
}

func parseWindows10EndpointProtectionConfigurationDefenderOfficeAppsExecutableContentCreationOrLaunchType(input string) (*Windows10EndpointProtectionConfigurationDefenderOfficeAppsExecutableContentCreationOrLaunchType, error) {
	vals := map[string]Windows10EndpointProtectionConfigurationDefenderOfficeAppsExecutableContentCreationOrLaunchType{
		"auditmode":   Windows10EndpointProtectionConfigurationDefenderOfficeAppsExecutableContentCreationOrLaunchTypeauditMode,
		"block":       Windows10EndpointProtectionConfigurationDefenderOfficeAppsExecutableContentCreationOrLaunchTypeblock,
		"disable":     Windows10EndpointProtectionConfigurationDefenderOfficeAppsExecutableContentCreationOrLaunchTypedisable,
		"userdefined": Windows10EndpointProtectionConfigurationDefenderOfficeAppsExecutableContentCreationOrLaunchTypeuserDefined,
		"warn":        Windows10EndpointProtectionConfigurationDefenderOfficeAppsExecutableContentCreationOrLaunchTypewarn,
	}
	if v, ok := vals[strings.ToLower(input)]; ok {
		return &v, nil
	}

	// otherwise presume it's an undefined value and best-effort it
	out := Windows10EndpointProtectionConfigurationDefenderOfficeAppsExecutableContentCreationOrLaunchType(input)
	return &out, nil
}
