package models

// Copyright (c) HashiCorp Inc. All rights reserved.
// Licensed under the MIT License. See NOTICE.txt in the project root for license information.

type IosGeneralDeviceConfiguration struct {
	AccountBlockModification                       *bool                                                `json:"accountBlockModification,omitempty"`
	ActivationLockAllowWhenSupervised              *bool                                                `json:"activationLockAllowWhenSupervised,omitempty"`
	AirDropBlocked                                 *bool                                                `json:"airDropBlocked,omitempty"`
	AirDropForceUnmanagedDropTarget                *bool                                                `json:"airDropForceUnmanagedDropTarget,omitempty"`
	AirPlayForcePairingPasswordForOutgoingRequests *bool                                                `json:"airPlayForcePairingPasswordForOutgoingRequests,omitempty"`
	AirPrintBlockCredentialsStorage                *bool                                                `json:"airPrintBlockCredentialsStorage,omitempty"`
	AirPrintBlocked                                *bool                                                `json:"airPrintBlocked,omitempty"`
	AirPrintBlockiBeaconDiscovery                  *bool                                                `json:"airPrintBlockiBeaconDiscovery,omitempty"`
	AirPrintForceTrustedTLS                        *bool                                                `json:"airPrintForceTrustedTLS,omitempty"`
	AppClipsBlocked                                *bool                                                `json:"appClipsBlocked,omitempty"`
	AppRemovalBlocked                              *bool                                                `json:"appRemovalBlocked,omitempty"`
	AppStoreBlockAutomaticDownloads                *bool                                                `json:"appStoreBlockAutomaticDownloads,omitempty"`
	AppStoreBlockInAppPurchases                    *bool                                                `json:"appStoreBlockInAppPurchases,omitempty"`
	AppStoreBlockUIAppInstallation                 *bool                                                `json:"appStoreBlockUIAppInstallation,omitempty"`
	AppStoreBlocked                                *bool                                                `json:"appStoreBlocked,omitempty"`
	AppStoreRequirePassword                        *bool                                                `json:"appStoreRequirePassword,omitempty"`
	AppleNewsBlocked                               *bool                                                `json:"appleNewsBlocked,omitempty"`
	ApplePersonalizedAdsBlocked                    *bool                                                `json:"applePersonalizedAdsBlocked,omitempty"`
	AppleWatchBlockPairing                         *bool                                                `json:"appleWatchBlockPairing,omitempty"`
	AppleWatchForceWristDetection                  *bool                                                `json:"appleWatchForceWristDetection,omitempty"`
	AppsSingleAppModeList                          *[]AppListItem                                       `json:"appsSingleAppModeList,omitempty"`
	AppsVisibilityList                             *[]AppListItem                                       `json:"appsVisibilityList,omitempty"`
	AppsVisibilityListType                         *IosGeneralDeviceConfigurationAppsVisibilityListType `json:"appsVisibilityListType,omitempty"`
	Assignments                                    *[]DeviceConfigurationAssignment                     `json:"assignments,omitempty"`
	AutoFillForceAuthentication                    *bool                                                `json:"autoFillForceAuthentication,omitempty"`
	AutoUnlockBlocked                              *bool                                                `json:"autoUnlockBlocked,omitempty"`
	BlockSystemAppRemoval                          *bool                                                `json:"blockSystemAppRemoval,omitempty"`
	BluetoothBlockModification                     *bool                                                `json:"bluetoothBlockModification,omitempty"`
	CameraBlocked                                  *bool                                                `json:"cameraBlocked,omitempty"`
	CellularBlockDataRoaming                       *bool                                                `json:"cellularBlockDataRoaming,omitempty"`
	CellularBlockGlobalBackgroundFetchWhileRoaming *bool                                                `json:"cellularBlockGlobalBackgroundFetchWhileRoaming,omitempty"`
	CellularBlockPerAppDataModification            *bool                                                `json:"cellularBlockPerAppDataModification,omitempty"`
	CellularBlockPersonalHotspot                   *bool                                                `json:"cellularBlockPersonalHotspot,omitempty"`
	CellularBlockPersonalHotspotModification       *bool                                                `json:"cellularBlockPersonalHotspotModification,omitempty"`
	CellularBlockPlanModification                  *bool                                                `json:"cellularBlockPlanModification,omitempty"`
	CellularBlockVoiceRoaming                      *bool                                                `json:"cellularBlockVoiceRoaming,omitempty"`
	CertificatesBlockUntrustedTlsCertificates      *bool                                                `json:"certificatesBlockUntrustedTlsCertificates,omitempty"`
	ClassroomAppBlockRemoteScreenObservation       *bool                                                `json:"classroomAppBlockRemoteScreenObservation,omitempty"`
	ClassroomAppForceUnpromptedScreenObservation   *bool                                                `json:"classroomAppForceUnpromptedScreenObservation,omitempty"`
	ClassroomForceAutomaticallyJoinClasses         *bool                                                `json:"classroomForceAutomaticallyJoinClasses,omitempty"`
	ClassroomForceRequestPermissionToLeaveClasses  *bool                                                `json:"classroomForceRequestPermissionToLeaveClasses,omitempty"`
	ClassroomForceUnpromptedAppAndDeviceLock       *bool                                                `json:"classroomForceUnpromptedAppAndDeviceLock,omitempty"`
	CompliantAppListType                           *IosGeneralDeviceConfigurationCompliantAppListType   `json:"compliantAppListType,omitempty"`
	CompliantAppsList                              *[]AppListItem                                       `json:"compliantAppsList,omitempty"`
	ConfigurationProfileBlockChanges               *bool                                                `json:"configurationProfileBlockChanges,omitempty"`
	ContactsAllowManagedToUnmanagedWrite           *bool                                                `json:"contactsAllowManagedToUnmanagedWrite,omitempty"`
	ContactsAllowUnmanagedToManagedRead            *bool                                                `json:"contactsAllowUnmanagedToManagedRead,omitempty"`
	ContinuousPathKeyboardBlocked                  *bool                                                `json:"continuousPathKeyboardBlocked,omitempty"`
	CreatedDateTime                                *string                                              `json:"createdDateTime,omitempty"`
	DateAndTimeForceSetAutomatically               *bool                                                `json:"dateAndTimeForceSetAutomatically,omitempty"`
	DefinitionLookupBlocked                        *bool                                                `json:"definitionLookupBlocked,omitempty"`
	Description                                    *string                                              `json:"description,omitempty"`
	DeviceBlockEnableRestrictions                  *bool                                                `json:"deviceBlockEnableRestrictions,omitempty"`
	DeviceBlockEraseContentAndSettings             *bool                                                `json:"deviceBlockEraseContentAndSettings,omitempty"`
	DeviceBlockNameModification                    *bool                                                `json:"deviceBlockNameModification,omitempty"`
	DeviceManagementApplicabilityRuleDeviceMode    *DeviceManagementApplicabilityRuleDeviceMode         `json:"deviceManagementApplicabilityRuleDeviceMode,omitempty"`
	DeviceManagementApplicabilityRuleOsEdition     *DeviceManagementApplicabilityRuleOsEdition          `json:"deviceManagementApplicabilityRuleOsEdition,omitempty"`
	DeviceManagementApplicabilityRuleOsVersion     *DeviceManagementApplicabilityRuleOsVersion          `json:"deviceManagementApplicabilityRuleOsVersion,omitempty"`
	DeviceSettingStateSummaries                    *[]SettingStateDeviceSummary                         `json:"deviceSettingStateSummaries,omitempty"`
	DeviceStatusOverview                           *DeviceConfigurationDeviceOverview                   `json:"deviceStatusOverview,omitempty"`
	DeviceStatuses                                 *[]DeviceConfigurationDeviceStatus                   `json:"deviceStatuses,omitempty"`
	DiagnosticDataBlockSubmission                  *bool                                                `json:"diagnosticDataBlockSubmission,omitempty"`
	DiagnosticDataBlockSubmissionModification      *bool                                                `json:"diagnosticDataBlockSubmissionModification,omitempty"`
	DisplayName                                    *string                                              `json:"displayName,omitempty"`
	DocumentsBlockManagedDocumentsInUnmanagedApps  *bool                                                `json:"documentsBlockManagedDocumentsInUnmanagedApps,omitempty"`
	DocumentsBlockUnmanagedDocumentsInManagedApps  *bool                                                `json:"documentsBlockUnmanagedDocumentsInManagedApps,omitempty"`
	EmailInDomainSuffixes                          *[]string                                            `json:"emailInDomainSuffixes,omitempty"`
	EnterpriseAppBlockTrust                        *bool                                                `json:"enterpriseAppBlockTrust,omitempty"`
	EnterpriseAppBlockTrustModification            *bool                                                `json:"enterpriseAppBlockTrustModification,omitempty"`
	EnterpriseBookBlockBackup                      *bool                                                `json:"enterpriseBookBlockBackup,omitempty"`
	EnterpriseBookBlockMetadataSync                *bool                                                `json:"enterpriseBookBlockMetadataSync,omitempty"`
	EsimBlockModification                          *bool                                                `json:"esimBlockModification,omitempty"`
	FaceTimeBlocked                                *bool                                                `json:"faceTimeBlocked,omitempty"`
	FilesNetworkDriveAccessBlocked                 *bool                                                `json:"filesNetworkDriveAccessBlocked,omitempty"`
	FilesUsbDriveAccessBlocked                     *bool                                                `json:"filesUsbDriveAccessBlocked,omitempty"`
	FindMyDeviceInFindMyAppBlocked                 *bool                                                `json:"findMyDeviceInFindMyAppBlocked,omitempty"`
	FindMyFriendsBlocked                           *bool                                                `json:"findMyFriendsBlocked,omitempty"`
	FindMyFriendsInFindMyAppBlocked                *bool                                                `json:"findMyFriendsInFindMyAppBlocked,omitempty"`
	GameCenterBlocked                              *bool                                                `json:"gameCenterBlocked,omitempty"`
	GamingBlockGameCenterFriends                   *bool                                                `json:"gamingBlockGameCenterFriends,omitempty"`
	GamingBlockMultiplayer                         *bool                                                `json:"gamingBlockMultiplayer,omitempty"`
	GroupAssignments                               *[]DeviceConfigurationGroupAssignment                `json:"groupAssignments,omitempty"`
	HostPairingBlocked                             *bool                                                `json:"hostPairingBlocked,omitempty"`
	IBooksStoreBlockErotica                        *bool                                                `json:"iBooksStoreBlockErotica,omitempty"`
	IBooksStoreBlocked                             *bool                                                `json:"iBooksStoreBlocked,omitempty"`
	ICloudBlockActivityContinuation                *bool                                                `json:"iCloudBlockActivityContinuation,omitempty"`
	ICloudBlockBackup                              *bool                                                `json:"iCloudBlockBackup,omitempty"`
	ICloudBlockDocumentSync                        *bool                                                `json:"iCloudBlockDocumentSync,omitempty"`
	ICloudBlockManagedAppsSync                     *bool                                                `json:"iCloudBlockManagedAppsSync,omitempty"`
	ICloudBlockPhotoLibrary                        *bool                                                `json:"iCloudBlockPhotoLibrary,omitempty"`
	ICloudBlockPhotoStreamSync                     *bool                                                `json:"iCloudBlockPhotoStreamSync,omitempty"`
	ICloudBlockSharedPhotoStream                   *bool                                                `json:"iCloudBlockSharedPhotoStream,omitempty"`
	ICloudPrivateRelayBlocked                      *bool                                                `json:"iCloudPrivateRelayBlocked,omitempty"`
	ICloudRequireEncryptedBackup                   *bool                                                `json:"iCloudRequireEncryptedBackup,omitempty"`
	ITunesBlockExplicitContent                     *bool                                                `json:"iTunesBlockExplicitContent,omitempty"`
	ITunesBlockMusicService                        *bool                                                `json:"iTunesBlockMusicService,omitempty"`
	ITunesBlockRadio                               *bool                                                `json:"iTunesBlockRadio,omitempty"`
	ITunesBlocked                                  *bool                                                `json:"iTunesBlocked,omitempty"`
	Id                                             *string                                              `json:"id,omitempty"`
	KeyboardBlockAutoCorrect                       *bool                                                `json:"keyboardBlockAutoCorrect,omitempty"`
	KeyboardBlockDictation                         *bool                                                `json:"keyboardBlockDictation,omitempty"`
	KeyboardBlockPredictive                        *bool                                                `json:"keyboardBlockPredictive,omitempty"`
	KeyboardBlockShortcuts                         *bool                                                `json:"keyboardBlockShortcuts,omitempty"`
	KeyboardBlockSpellCheck                        *bool                                                `json:"keyboardBlockSpellCheck,omitempty"`
	KeychainBlockCloudSync                         *bool                                                `json:"keychainBlockCloudSync,omitempty"`
	KioskModeAllowAssistiveSpeak                   *bool                                                `json:"kioskModeAllowAssistiveSpeak,omitempty"`
	KioskModeAllowAssistiveTouchSettings           *bool                                                `json:"kioskModeAllowAssistiveTouchSettings,omitempty"`
	KioskModeAllowAutoLock                         *bool                                                `json:"kioskModeAllowAutoLock,omitempty"`
	KioskModeAllowColorInversionSettings           *bool                                                `json:"kioskModeAllowColorInversionSettings,omitempty"`
	KioskModeAllowRingerSwitch                     *bool                                                `json:"kioskModeAllowRingerSwitch,omitempty"`
	KioskModeAllowScreenRotation                   *bool                                                `json:"kioskModeAllowScreenRotation,omitempty"`
	KioskModeAllowSleepButton                      *bool                                                `json:"kioskModeAllowSleepButton,omitempty"`
	KioskModeAllowTouchscreen                      *bool                                                `json:"kioskModeAllowTouchscreen,omitempty"`
	KioskModeAllowVoiceControlModification         *bool                                                `json:"kioskModeAllowVoiceControlModification,omitempty"`
	KioskModeAllowVoiceOverSettings                *bool                                                `json:"kioskModeAllowVoiceOverSettings,omitempty"`
	KioskModeAllowVolumeButtons                    *bool                                                `json:"kioskModeAllowVolumeButtons,omitempty"`
	KioskModeAllowZoomSettings                     *bool                                                `json:"kioskModeAllowZoomSettings,omitempty"`
	KioskModeAppStoreUrl                           *string                                              `json:"kioskModeAppStoreUrl,omitempty"`
	KioskModeAppType                               *IosGeneralDeviceConfigurationKioskModeAppType       `json:"kioskModeAppType,omitempty"`
	KioskModeBlockAutoLock                         *bool                                                `json:"kioskModeBlockAutoLock,omitempty"`
	KioskModeBlockRingerSwitch                     *bool                                                `json:"kioskModeBlockRingerSwitch,omitempty"`
	KioskModeBlockScreenRotation                   *bool                                                `json:"kioskModeBlockScreenRotation,omitempty"`
	KioskModeBlockSleepButton                      *bool                                                `json:"kioskModeBlockSleepButton,omitempty"`
	KioskModeBlockTouchscreen                      *bool                                                `json:"kioskModeBlockTouchscreen,omitempty"`
	KioskModeBlockVolumeButtons                    *bool                                                `json:"kioskModeBlockVolumeButtons,omitempty"`
	KioskModeBuiltInAppId                          *string                                              `json:"kioskModeBuiltInAppId,omitempty"`
	KioskModeEnableVoiceControl                    *bool                                                `json:"kioskModeEnableVoiceControl,omitempty"`
	KioskModeManagedAppId                          *string                                              `json:"kioskModeManagedAppId,omitempty"`
	KioskModeRequireAssistiveTouch                 *bool                                                `json:"kioskModeRequireAssistiveTouch,omitempty"`
	KioskModeRequireColorInversion                 *bool                                                `json:"kioskModeRequireColorInversion,omitempty"`
	KioskModeRequireMonoAudio                      *bool                                                `json:"kioskModeRequireMonoAudio,omitempty"`
	KioskModeRequireVoiceOver                      *bool                                                `json:"kioskModeRequireVoiceOver,omitempty"`
	KioskModeRequireZoom                           *bool                                                `json:"kioskModeRequireZoom,omitempty"`
	LastModifiedDateTime                           *string                                              `json:"lastModifiedDateTime,omitempty"`
	LockScreenBlockControlCenter                   *bool                                                `json:"lockScreenBlockControlCenter,omitempty"`
	LockScreenBlockNotificationView                *bool                                                `json:"lockScreenBlockNotificationView,omitempty"`
	LockScreenBlockPassbook                        *bool                                                `json:"lockScreenBlockPassbook,omitempty"`
	LockScreenBlockTodayView                       *bool                                                `json:"lockScreenBlockTodayView,omitempty"`
	ManagedPasteboardRequired                      *bool                                                `json:"managedPasteboardRequired,omitempty"`
	MediaContentRatingApps                         *IosGeneralDeviceConfigurationMediaContentRatingApps `json:"mediaContentRatingApps,omitempty"`
	MediaContentRatingAustralia                    *MediaContentRatingAustralia                         `json:"mediaContentRatingAustralia,omitempty"`
	MediaContentRatingCanada                       *MediaContentRatingCanada                            `json:"mediaContentRatingCanada,omitempty"`
	MediaContentRatingFrance                       *MediaContentRatingFrance                            `json:"mediaContentRatingFrance,omitempty"`
	MediaContentRatingGermany                      *MediaContentRatingGermany                           `json:"mediaContentRatingGermany,omitempty"`
	MediaContentRatingIreland                      *MediaContentRatingIreland                           `json:"mediaContentRatingIreland,omitempty"`
	MediaContentRatingJapan                        *MediaContentRatingJapan                             `json:"mediaContentRatingJapan,omitempty"`
	MediaContentRatingNewZealand                   *MediaContentRatingNewZealand                        `json:"mediaContentRatingNewZealand,omitempty"`
	MediaContentRatingUnitedKingdom                *MediaContentRatingUnitedKingdom                     `json:"mediaContentRatingUnitedKingdom,omitempty"`
	MediaContentRatingUnitedStates                 *MediaContentRatingUnitedStates                      `json:"mediaContentRatingUnitedStates,omitempty"`
	MessagesBlocked                                *bool                                                `json:"messagesBlocked,omitempty"`
	NetworkUsageRules                              *[]IosNetworkUsageRule                               `json:"networkUsageRules,omitempty"`
	NfcBlocked                                     *bool                                                `json:"nfcBlocked,omitempty"`
	NotificationsBlockSettingsModification         *bool                                                `json:"notificationsBlockSettingsModification,omitempty"`
	ODataType                                      *string                                              `json:"@odata.type,omitempty"`
	OnDeviceOnlyDictationForced                    *bool                                                `json:"onDeviceOnlyDictationForced,omitempty"`
	OnDeviceOnlyTranslationForced                  *bool                                                `json:"onDeviceOnlyTranslationForced,omitempty"`
	PasscodeBlockFingerprintModification           *bool                                                `json:"passcodeBlockFingerprintModification,omitempty"`
	PasscodeBlockFingerprintUnlock                 *bool                                                `json:"passcodeBlockFingerprintUnlock,omitempty"`
	PasscodeBlockModification                      *bool                                                `json:"passcodeBlockModification,omitempty"`
	PasscodeBlockSimple                            *bool                                                `json:"passcodeBlockSimple,omitempty"`
	PasscodeExpirationDays                         *int64                                               `json:"passcodeExpirationDays,omitempty"`
	PasscodeMinimumCharacterSetCount               *int64                                               `json:"passcodeMinimumCharacterSetCount,omitempty"`
	PasscodeMinimumLength                          *int64                                               `json:"passcodeMinimumLength,omitempty"`
	PasscodeMinutesOfInactivityBeforeLock          *int64                                               `json:"passcodeMinutesOfInactivityBeforeLock,omitempty"`
	PasscodeMinutesOfInactivityBeforeScreenTimeout *int64                                               `json:"passcodeMinutesOfInactivityBeforeScreenTimeout,omitempty"`
	PasscodePreviousPasscodeBlockCount             *int64                                               `json:"passcodePreviousPasscodeBlockCount,omitempty"`
	PasscodeRequired                               *bool                                                `json:"passcodeRequired,omitempty"`
	PasscodeRequiredType                           *IosGeneralDeviceConfigurationPasscodeRequiredType   `json:"passcodeRequiredType,omitempty"`
	PasscodeSignInFailureCountBeforeWipe           *int64                                               `json:"passcodeSignInFailureCountBeforeWipe,omitempty"`
	PasswordBlockAirDropSharing                    *bool                                                `json:"passwordBlockAirDropSharing,omitempty"`
	PasswordBlockAutoFill                          *bool                                                `json:"passwordBlockAutoFill,omitempty"`
	PasswordBlockProximityRequests                 *bool                                                `json:"passwordBlockProximityRequests,omitempty"`
	PkiBlockOTAUpdates                             *bool                                                `json:"pkiBlockOTAUpdates,omitempty"`
	PodcastsBlocked                                *bool                                                `json:"podcastsBlocked,omitempty"`
	PrivacyForceLimitAdTracking                    *bool                                                `json:"privacyForceLimitAdTracking,omitempty"`
	ProximityBlockSetupToNewDevice                 *bool                                                `json:"proximityBlockSetupToNewDevice,omitempty"`
	RoleScopeTagIds                                *[]string                                            `json:"roleScopeTagIds,omitempty"`
	SafariBlockAutofill                            *bool                                                `json:"safariBlockAutofill,omitempty"`
	SafariBlockJavaScript                          *bool                                                `json:"safariBlockJavaScript,omitempty"`
	SafariBlockPopups                              *bool                                                `json:"safariBlockPopups,omitempty"`
	SafariBlocked                                  *bool                                                `json:"safariBlocked,omitempty"`
	SafariCookieSettings                           *IosGeneralDeviceConfigurationSafariCookieSettings   `json:"safariCookieSettings,omitempty"`
	SafariManagedDomains                           *[]string                                            `json:"safariManagedDomains,omitempty"`
	SafariPasswordAutoFillDomains                  *[]string                                            `json:"safariPasswordAutoFillDomains,omitempty"`
	SafariRequireFraudWarning                      *bool                                                `json:"safariRequireFraudWarning,omitempty"`
	ScreenCaptureBlocked                           *bool                                                `json:"screenCaptureBlocked,omitempty"`
	SharedDeviceBlockTemporarySessions             *bool                                                `json:"sharedDeviceBlockTemporarySessions,omitempty"`
	SiriBlockUserGeneratedContent                  *bool                                                `json:"siriBlockUserGeneratedContent,omitempty"`
	SiriBlocked                                    *bool                                                `json:"siriBlocked,omitempty"`
	SiriBlockedWhenLocked                          *bool                                                `json:"siriBlockedWhenLocked,omitempty"`
	SiriRequireProfanityFilter                     *bool                                                `json:"siriRequireProfanityFilter,omitempty"`
	SoftwareUpdatesEnforcedDelayInDays             *int64                                               `json:"softwareUpdatesEnforcedDelayInDays,omitempty"`
	SoftwareUpdatesForceDelayed                    *bool                                                `json:"softwareUpdatesForceDelayed,omitempty"`
	SpotlightBlockInternetResults                  *bool                                                `json:"spotlightBlockInternetResults,omitempty"`
	SupportsScopeTags                              *bool                                                `json:"supportsScopeTags,omitempty"`
	UnpairedExternalBootToRecoveryAllowed          *bool                                                `json:"unpairedExternalBootToRecoveryAllowed,omitempty"`
	UsbRestrictedModeBlocked                       *bool                                                `json:"usbRestrictedModeBlocked,omitempty"`
	UserStatusOverview                             *DeviceConfigurationUserOverview                     `json:"userStatusOverview,omitempty"`
	UserStatuses                                   *[]DeviceConfigurationUserStatus                     `json:"userStatuses,omitempty"`
	Version                                        *int64                                               `json:"version,omitempty"`
	VoiceDialingBlocked                            *bool                                                `json:"voiceDialingBlocked,omitempty"`
	VpnBlockCreation                               *bool                                                `json:"vpnBlockCreation,omitempty"`
	WallpaperBlockModification                     *bool                                                `json:"wallpaperBlockModification,omitempty"`
	WiFiConnectOnlyToConfiguredNetworks            *bool                                                `json:"wiFiConnectOnlyToConfiguredNetworks,omitempty"`
	WiFiConnectToAllowedNetworksOnlyForced         *bool                                                `json:"wiFiConnectToAllowedNetworksOnlyForced,omitempty"`
	WifiPowerOnForced                              *bool                                                `json:"wifiPowerOnForced,omitempty"`
}
